### ISSUE TITLE
State of emitter and entities plugins

### ISSUE THREAD

**Issue by piernik** [ngxs/store#1077]
I'm starting new project and I can see that there are two interesting plugins in labs: https://github.com/ngxs-labs/emitter and https://github.com/ngxs-labs/entity-state

I'd like to know will those plugins get to main `ngxs` package?
Can I use it in production hoping that they will be maintained?

**Comment by splincode** [comment]
Unfortunately, these packages are developed solely in order to assess whether their approaches can be worthy in order to get into the main repository. And the opinions of the main team diverge.

At work, I actively use https://github.com/ngxs-labs/emitter

In some places it is very inconvenient, but in many ways it is pleasant to use it.

https://github.com/ngxs-labs/entity-state
It is not the main project now and it is engaged in one entity-state now
