### ISSUE TITLE
How to name actions when they do the same thing from two different sources ?

### ISSUE THREAD

**Issue by chaouiy** [ngxs/store#1122]
I need to update article from two different pages. I created two classes with types :

* ` [articles page] UpdateArticle`. 
* `[home page] UpdateArticle`. 

Since action class name doesn't contain what is between brackets I will get two action class with same name `UpdateArticle` . 

How to handle this ? And why ngxs need type field + class name, isn't it redundunt.

**Comment by internalsystemerror** [comment]
Afaik, the type field is what is checked to be a unique action, the class name is too short and can conflict since there are no namespaces.

e.g. I have two different classses (named differently) that share the same type string... They will conflict... Having two different classes (named the same) that have different type strings, don't conflict.

**Comment by chaouiy** [comment]
Ok. So I just need to move the second to a new file.

**Comment by arturovt** [comment]
Should it be closed if resolved?
