### ISSUE TITLE
🐞[BUG]: Handling errors in NGXS (angular) with global error handler

### ISSUE THREAD

**Issue by cmaart** [ngxs/store#1145]
Basically this question here:

https://stackoverflow.com/questions/56872587/handling-errors-in-ngxs-angular-with-global-error-handler

I can't find a way to use a global error handler as fallback only when an error is not handled by the dispatching component. Other good ways of handling errors appreciated.

**Comment by joaqcid** [comment]
I think the way you are supposed to do this is handle the error in the action, if an unhandled exception happens, that's when your fallback global error handler would handle it.

**Comment by cmaart** [comment]
If I'd do that there would be still the problem of the global error handler being called twice when subscribing on the store when calling dispatch. I've written the global error handler to detect duplicates but certainly I don't find this ideal

**Comment by fikkatra** [comment]
For those of you, like me, still running into the issue of errors being processed by the `ErrorHandler` even when they are caught, or errors that are **processed twice** by the `ErrorHandler` when they are not caught, we found a solution to bypass this behaviour.

To summarize:

Desired behaviour:
- errors that aren't caught within the action handler, but are caught later (e.g. by the dispatcher), should not be handled by `ErrorHandler`
- errors that aren't caught anywhere and bubble up, should be handled by `ErrorHandler`, but only once

Observed behaviour:
- errors that aren't caught within the action handler, but are caught later (e.g. by the dispatcher), ARE handled by `ErrorHandler`
- errors that aren't caught anywhere and bubble up, are be handled by `ErrorHandler`, but they are handled TWICE (once because NGXS calls `ErrorHandler`, once because Angular calls `ErrorHandler`)

**Solution:**
Unfortunately, NGXS ALWAYS calls `ErrorHandler` when an error leaves the action handler, there's no way to prevent this (see [this comment](https://github.com/ngxs/store/issues/803#issuecomment-565170651)). The only thing you can do, is customize the logic in `ErrorHandler` so it can detect whether it is called by ngxs (rather than by Angular for uncaught errors), and have a duplicate detection system to ignore errors.

To do this, write an NgxsPlugin that hooks into the ngxs pipe:
```
import { Injectable } from '@angular/core';
import { catchError } from 'rxjs/operators';
import { NgxsPlugin } from '@ngxs/store';
import { ErrorConstants } from './models/error-constants';

@Injectable()
export class NgxsErrorPlugin implements NgxsPlugin {
  public handle(state: any, action: any, next: any): void {
    return next(state, action).pipe(
      catchError((error) => {
        error['skipErrorFlag'] = true;
        throw error;
      }),
    );
  }
}
```

Write a custom ErrorHandler:
```
@Injectable({
  providedIn: 'root',
})
export class CustomErrorHandler implements ErrorHandler {
  constructor(private customLogger: Logger) {}

  public handleError(error: any): void {
    if (error['skipError'] && !error['errorSkipped']) {
      error['errorSkipped'] = true;
      // ignore error
      return;
    }

    this.customLogger.error(error);
    this.handleUncaughtError(error);
  }

  private handleUncaughtError(err: any): void {
    // implement logic for uncaught errors
  }
}
```

Provide both the plugin and the custom `ErrorHandler`:
```
import { ErrorHandler, NgModule } from '@angular/core';
import { NGXS_PLUGINS } from '@ngxs/store';
import { CustomErrorHandler } from './services/custom-error-handler';
import { NgxsErrorPlugin } from './ngxs-errors-plugin';

@NgModule({
  // imports, exports, declarations...
  providers: [
    { provide: ErrorHandler, useClass: CustomErrorHandler },
    {
      provide: NGXS_PLUGINS,
      useClass: NgxsErrorPlugin,
      multi: true,
    },
  ],
})
export class AppModule {}
```

It's hacky, but at least it enables you to let the dispatcher (rather than the action handler) decide whether it wants to catch/handle the error or not, and have a mechanism to handle errors that aren't caught anywhere.

**Comment by MatheusBrito174** [comment]
@fikkatra It seems to me that ultimately what we want to do is simply prevent the same error object from being handled twice by the ErrorHandler. At least I can't think of any scenario where that would be the expected behavior. If so, can't we just set the flag in the ErrorHandler itself? Asking because I feel like I might be missing something.

Something like this:

```
@Injectable()
export class CustomErrorHandler implements ErrorHandler {
  handleError(error: any): void {
    /*
     * Prevent scenario where error gets handled twice for
     * any reason.
     */
    if (error.alreadyHandledInErrorHandler) {
      return;
    }

    error.alreadyHandledInErrorHandler= true;

    // do stuff with the error
  }
}
```

**Comment by fikkatra** [comment]
> @fikkatra First of all, thank you for providing this solution.
> 
> It seems to me that ultimately what we want to do is simply prevent the same error object from being handled twice by the ErrorHandler. At least I can't think of any scenario where that would be the expected behavior. If so, can't we just set the flag in the ErrorHandler itself? Asking because I feel like I might be missing something.
> 
> Something like this:
> 
> ```
> @Injectable()
> export class CustomErrorHandler implements ErrorHandler {
>   handleError(error: any): void {
>     /*
>      * Prevent scenario where error gets handled twice for
>      * any reason.
>      */
>     if (error.alreadyHandledInErrorHandler) {
>       return;
>     }
> 
>     error.alreadyHandledInErrorHandler= true;
> 
>     // do stuff with the error
>   }
> }
> ```

@MatheusBrito174 your code is definitely more simple and might perfectly work for some project setups. However, there are definitely scenario's/setups which justify the more complex setup. The reason why my code sample is more complex, is because we need to control over _which time_ the error is handled by the error handler, if at all. Consider the following scenario's:

- error is thrown by ngxs (and passes custom error handler)
- Scenario A: error is gracefully handled by the component (and thus it does not bubble up to the custom error handler) 
- Scenario B: error is not handled by the component (and bubbles up to the custom error handler)

In scenario A, we don't want the error to be handled by the custom error handler at all, since it is already gracefully handled by the component. That's why it is important that the custom error handler **ignores the error the first time** it passes there.

Similar for scenario B: we want the custom error handler to **handle the error only the second time** it passes there, because that's the only time we know for sure that it wasn't already gracefully handled by a component.

With your simplified version of the code, the error will always be handled the first time it passes the custom error handler. In this case, it is not possible for the component to handle the error gracefully, without the custom error handling logic kicking in.

In our case, the custom error handler shows a 'something went wrong' popup. However, some errors, like HTTP 404, require a more custom approach implemented within the component (e.g. 'we couldn't find this task. Would you like to create a new one?'). In that case it is important the general 'something went wrong' error popup is not displayed to the user. Therefore, we should ignore the error in the custom error handler, until we are sure that it isn't handled gracefully.

**Comment by MatheusBrito174** [comment]
@fikkatra I see. Thanks a lot for explaining. I knew I was misunderstanding something.
