### ISSUE TITLE
router-plugin bug v3.5.0 when use baseHref

### ISSUE THREAD

**Issue by Jimmysh** [ngxs/store#1174]
## I'm submitting a...

<pre><code>
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

baseHref in url will be copy once when you refresh browser. 

## Minimal reproduction of the problem with instructions

 Step 1
use baseHref in angular.json
```
{
 "baseHref": "/en/"
}
```
 Step 2
```
ng serve
```
 Step 3
refresh you browser
## Environment

<pre><code>
Libs:
- @angular/core version: X.Y.Z
- @ngxs/store version: X.Y.Z

Browser:
- [ x ] Chrome (desktop) version 75.0.3770.142
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.16.0 
- Platform:  Mac 

Others:

</code></pre>

**Comment by markwhitfeld** [comment]
@arturovt Could this be related to PR #1159 and the fix for issue #1153?

**Comment by markwhitfeld** [comment]
Please could you provide a repo or stackblitz demonstrating the issue?

**Comment by Jimmysh** [comment]
@maartentibau 
I can't provide repo demonstrating my issue now. 

https://github.com/Jimmysh/angular-stackblitz/tree/ngxs
this repo can demo NgxsRouterPlugin V3.5.0  not support baseHref. but 3.4.3 is good.

**Comment by arturovt** [comment]
@Jimmysh that's better :)

**Comment by Dav1dde** [comment]
I just ran into the same issue when setting `APP_BASE_HREF` dynamically during SSR.

The router recognizes the initial route correctly (with stripped baseHref), this triggers the router plugin, which then in turn performs an additional navigation:
![image](https://user-images.githubusercontent.com/255721/61887410-d8e19000-af01-11e9-8023-4e7b0540560e.png)

to the non-baseHref-stripped URL, because `currentSerializedUrl != currentUrl`. The linked PR #1178 should be working, since `normalize` strips the baseHref: 
![image](https://user-images.githubusercontent.com/255721/61887640-4f7e8d80-af02-11e9-9918-6903f7742e7b.png)

**Comment by arturovt** [comment]
@Dav1dde Thanks for investigation and additional help, we appreciate that :tada:

**Comment by goldenass** [comment]
Sorry if I ask, but that is a major obstacle for using the library in an actual project. I am now using the @dev version, but I think that lots of people will fill far more confortable being able to depend on a real realse (3.5.1 ???). When such release is planned to rollout?

**Comment by splincode** [comment]
@markwhitfeld ping

**Comment by johnwalshuk** [comment]
Could we get patch release for this? or should i downgrade the dependency?

**Comment by markwhitfeld** [comment]
Released in v3.5.1! Please test.
