### ISSUE TITLE
🚀[FEATURE]: Router state should be always up-to-date

### ISSUE THREAD

**Issue by piernik** [ngxs/store#1307]
### Relevant Package
@ngxs/router-plugin

### Description
In my `guard` I want to use `ngxs` to fetch `ActivatedRoute` params, data and queryParams.
But in store there are none up-to-date of them :/

As I see In source: https://github.com/ngxs/store/blob/master/packages/router-plugin/src/router.state.ts there is no hack for `GuardsCheckStart` or even `ActivationStart`. I think it should be.

### Describe the solution you'd like
When navigation starts all new params, data and queryParams should be in store. If guards fail state should be reverted. But always should be Up-to-date.

Edit:

I looked into source code. I think You can add to `setUpStateRollbackEvents()`
```
} else if (e instanceof GuardsCheckStart) {
        this.guardsCheckEnd(e.state);
      } else if (e instanceof ResolveStart) {
        this.guardsCheckEnd(e.state);
```
It will populate state with `next` data. You can add checking `navigationId` so that dispatch won't be triggered multiple times.

**Comment by arturovt** [comment]
We're open to PRs! :)

**Comment by piernik** [comment]
@arturovt I tired but I'm not 'fluent' with github and commits and forks and so on... Maybe I can nly post changed file?

**Comment by arturovt** [comment]
> In my guard I want to use ngxs to fetch ActivatedRoute params, data and queryParams

I think you're over-complicating your problem. Angular already provides an instance of the `ActivatedRouteSnapshot` to guards method signatures:

```ts
canActivate(route: ActivatedRouteSnapshot) {
  console.log(route.params);
  console.log(route.queryParams);
}
```

I'm closing this issue not because I do not wanna implement additional feature for you. No, for sure. This is the problem that should not be solved with state management as I've showed in the example above. `@ngrx/router-store` also does not provide listeners for those actions like `GuardsCheckStart|ActivationStart`. Their behavior is not deterministic, that's what I know from my experience supporting this router plugin.
