### ISSUE TITLE
Payload not shown using DevTools

### ISSUE THREAD

**Issue by mailok** [ngxs/store#132]
### Versions

```
* ngxs: 2.0.0-rc.18
* @angular/core: 5.2.9
```

### Repro steps

*  Clone repository https://github.com/ngxs/core
*  I run start:integration script
*  add Todo test

### Observed behavior

runs  AddTodo acction

![captura](https://user-images.githubusercontent.com/3769277/37775053-3ba22b7c-2db8-11e8-9669-719613516e61.PNG)

### Desired behavior

Only shows the name of the action: AddTodo
Does not show the payload

**Comment by amcdnl** [comment]
Fixed in rc20

**Comment by leon** [comment]
@amcdnl 
I prefer writing my actions as follows

```TS
class AddUser {
  constructor(public user: User) {}
}
```

To make it more explicit what the action contains.
It could also contain more fields

```TS
class MoveFolder {
  constructor(public fromDir: string, public toDir: string) {}
}
```

it's easier in the handler to then get the action as a parameter and have type completion directly on the action instead of having to destructure the payload.

This means that the this code will not work for my scenario. Maybe we should extract the type from the class and then add the classes fields and send that?

What do you think?

**Comment by amcdnl** [comment]
Fixed! :)
