### ISSUE TITLE
NgxsLocalStoragePluginModule always picks localStorage as storage option

### ISSUE THREAD

**Issue by perjansson** [ngxs/store#140]
### Versions

```
* ngxs: 2.0.0-rc.18
* @angular/core: 5.2.1
```

### Repro steps

When configuring `NgxsLocalStoragePluginModule` to use sessionStorage as storage engine like this is does not work.

```
NgxsLocalStoragePluginModule.forRoot({
	key: STORAGE_KEY_NGXS_STORE,
	storage: sessionStorage,
})
```

### Observed behavior

It still saves state into `localStorage`.

### Desired behavior

Saves state into `sessionStorage`

**Comment by amcdnl** [comment]
Can you see whats getting set here? https://github.com/ngxs/core/blob/master/src/plugins/localstorage/localstorage.plugin.ts#L14

**Comment by perjansson** [comment]
@amcdnl It's the localStorage getting set there. I added one item to `sessionStorage` with the name of `"sessionStorage"` and one item to `localStorage` with the name of "`localStorage"`. When I debug I can see that it is the Storage that has the item "localStorage" that comes in option.storage and is assigned the engine.

<img width="1640" alt="engine" src="https://user-images.githubusercontent.com/1557938/37851470-49a9ccde-2edf-11e8-86de-ba7c7e77b39a.png">

**Comment by un33k** [comment]
@amcdnl It turns out that Angular passes `null` for anything that cannot be serialized.  In this case, localStorage and sessionStorage seem not to be serializable.

Since I recommended this approach, I went ahead and fixed the issue and while at it, I cleanup storage a bit as well.  Since we support `localStorage` & `sessionStorage`, I renamed the module `storage` instead of `localstorage`.

Docs were modified to reflect the changes.
Added tests for sessionStorage as well.

Hope this helps.

Here is the PR:  https://github.com/ngxs/store/pull/152
