### ISSUE TITLE
🚀[FEATURE]: Dynamic change options for Logger, Devtools plugins

### ISSUE THREAD

**Issue by splincode** [ngxs/store#1417]
### Description

I'm on 3.5.1 and it seems that things are still initialized before APP_INITIALIZER.
Not sure if I'm missing something or if I don't completely understand what this issue's resolution should be?

This is my use case:
I need to initialize Ngxs through a library module that either is imported or not in the apps (monorepo structure)
And I couldn’t find a way to initialize it properly (the apps that import it should pass further if production is true or not, since a library shouldn't care about the app's environment directly)
But it seems that the initialization still takes place before APP_INITIALIZER resolves
This is my stackblitz: https://stackblitz.com/edit/ngxs-app-initializer?file=src%2Fapp%2Fstore%2Fstore.module.ts
The console will show:

prev state
next state
APP_INITIALIZER
APP_INITIALIZER Resolved
NGXS Logger shouldn't log anymore (but it does)
payload
prev state
next state
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
but it should have production: true (I pass that hardcoded, since I don't have environments in the stackblitz) and developmentMode should be false. Also, the logger shouldn’t log.

P.S. Because of hmr, you need to reload the right-side browser window every time you make a change (at first I was tempted to think that the problem was resolved because of HMR, I wouldn't get the console logs all the time... but pressing reload shows every time that ngxs initializes before APP_INITIALIZER resolves)

### Describe the solution you'd like

```ts
class DashboardComponent {
   constructor(private loggerPlugin: NgxsLoggerPlugin) {}

   public ngOnInit() {
     this.loggerPlugin.options({ disable: true });
   }
}
```

**Comment by MrCroft** [comment]
Thanks for opening this @splincode !

Using a monorepo structure here (multiple apps sharing libs), mimicking nrwl/nx, but at a smaller scale, just using the Angular CLI, without Nrwl Schematics.

**Goal:**
Have an NgModule lib that initializes an Ngxs store (with some core states that are the same for all apps consuming the store lib/module):
```
import { NgModule, ModuleWithProviders, APP_INITIALIZER } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NgxsModule } from '@ngxs/store';
import { NgxsLoggerPluginModule } from '@ngxs/logger-plugin';
import { NgxsReduxDevtoolsPluginModule } from '@ngxs/devtools-plugin';

export interface StoreOptions {
  production: boolean;
};

@NgModule({
  imports: [
    CommonModule,
    NgxsModule.forRoot(DEFAULT_STATES, { developmentMode: !<production> }),
    NgxsReduxDevtoolsPluginModule.forRoot({ disabled: <production> }),
    NgxsLoggerPluginModule.forRoot({ disabled: <production> })
  ],
  exports: [NgxsModule]
})
export class MyLibStoreModule {
  static forRoot(options: StoreOptions): ModuleWithProviders {
    return {
      ngModule: MyLibStoreModule,
      providers: [
        {
          // I think we should be able to use APP_INITIALIZER somehow
          // and be able to pass options.production to the initialization logic in the `@NgModule` above
          // See StackBlitz example: https://stackblitz.com/edit/ngxs-app-initializer?file=src%2Fapp%2Fstore%2Fstore.module.ts
          // I've followed a solution presented for Firebase initialization, under the same scenario, here: https://github.com/nrwl/nx/issues/208#issuecomment-536169371
          // but doesn't seem to work in production build: Function expressions are not supported in decorators
        }
      ]
    };
  }
}
```

**Issue:**
When we import `MyLibStoreModule` in an app, we should be able to tell it the value of `environment.production` (since libs aren't/shouldn't be aware of the environment of the app that consumes the library) which should be used further in the logic inside the `@NgModule` decorator of `MyLibStoreModule`:
```
@NgModule({
  declarations: [AppComponent],
  imports: [
    // ...
    MyLibStoreModule.forRoot({ production: environment.production })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

I'm not sure if "dynamically changing options for ngxs and plugins (logger, devtools)" would be the solution, since the (boolean) value should already be known at initialization time (`NgxsModule.forRoot( ... )`).
Being able to change options would actually mean "first  initialize assuming we're in production mode (so, disable logger, devtools, set developmentMode: false for Ngxs), and then change options if not production".
My understanding of the how APP_INITIALIZER should work is  that "nothing should happen until the APP_INITIALIZER resolves", so I would have expected these imports:
```
@NgModule({
    NgxsModule.forRoot(DEFAULT_STATES, { developmentMode: !<production> }),
    NgxsReduxDevtoolsPluginModule.forRoot({ disabled: <production> }),
    NgxsLoggerPluginModule.forRoot({ disabled: <production> })
})
```
to "wait" for the appropriate value.
If my understanding was wrong, I'm not sure what the solution would be...

**Comment by splincode** [comment]
@MrCroft what do you think about

```ts
@NgModule({
  imports: [ CommonModule ],
  exports: [ NgxsModule ]
})
export class MyLibStoreModule {
  static forRoot(states: Type<any>[], production: boolean, options: StoreOptions): ModuleWithProviders<any>[ ] {
    return [
     NgxsModule.forRoot(states, { developmentMode: production }),
NgxsReduxDevtoolsPluginModule.forRoot({ disabled: production }),
    NgxsLoggerPluginModule.forRoot({ disabled: production }),
     {
      ngModule: MyLibStoreModule,
      providers: [ /*.. */]
     }
     ]
    };
  }
}
```

**Comment by MrCroft** [comment]
@splincode makes perfect sense. Why didn't this occur to me, I don't know... I was going about it the harder way.
Thank you! Just tried it out, works perfectly of course!
Sorry for the trouble!

**Comment by splincode** [comment]
Do not close, I will update docs for "Dynamic Plugins"

**Comment by arturovt** [comment]
Can be closed?
