### ISSUE TITLE
🚀[FEATURE]: Dispatch navigation action on RoutesRecognized router event

### ISSUE THREAD

**Issue by klinem** [ngxs/store#1533]
### Relevant Package

 This feature request is for @ngxs/router-plugin

### Description
 Allow for the RouterNavigation action to be dispatched when the RoutesRecognized event occurs.

### Describe the problem you are trying to solve
  A router navigation action is only dispatched on certain router events. This is a problem when using multiple "levels" of router guards that rely on a piece of state that are also dependent on the state of the router. I've put together this to illustrate the issue better:

[https://stackblitz.com/edit/angular-kulrbd?embed=1](https://stackblitz.com/edit/angular-kulrbd?embed=1)

Firstly, click on "Project A", it will then load the project issues, clicking on either issue then loads the issue details. This all works fine, the problem comes in when you try to navigate directly to the [issue details screen](https://angular-kulrbd.stackblitz.io/projects/1/issues/1) which now fails due to the "currentProject" being undefined. The issues state is dependent on the current project state, which is determined by the "projectId" router param; which is not yet available as part of the RouterState as the plugin will only update the state once the GuardsCheckEnd event has been fired; which seems to wait for all guards to be completed.

If you uncomment lines [121-123 of the ngxs-router-plugin-patch/router.state.ts](https://stackblitz.com/edit/angular-kulrbd?embed=1&file=src/app/ngxs-router-plugin-patch/router.state.ts) of the provided StackBlitz, the app then works as expected when navigating directly to the [issue details screen](https://angular-kulrbd.stackblitz.io/projects/1/issues/1).

### Describe the solution you'd like

Similar to NGRX, I'd like to be able to configure the [Navigation action timing](https://github.com/ngrx/platform/blob/4cae255cdbc25ed9c19c3cf3a4025e05b60fec1a/modules/router-store/src/router_store_module.ts#L235) to allow for either pre or post activation events which will update the router state. 

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by troydietz** [comment]
@klinem I think your proposed solution to your problem would undo the work done to fix issue #1605

Would having two router states available through the router plugin fix your problem?  Something like `currentRouteState` and `nextRouteState`.  I'm imagining all route guards and resolvers would be interested in `nextRouteState` and all components would be interested in `currentRouteState`.

My idea is regarding the timing or sequencing:`currentRouteState` would become `nextRouteState` after angular fires `NavigationEnd` event.  Otherwise angular will fire a `NavigationCancel` or `NavigationError` event at which point `currentRouteState` would not become `nextRouteState`

**Comment by arturovt** [comment]
Thank you for submitting this feature request.
We are closing this issue due to the fact that:
- This feature is not currently planned for the future
- There has not been much support from other community members
You are welcome to re-open this issue with a further motivation for why this feature is essential for the core library or plugins.
If you would like to pursue the implementation of this feature we would encourage you to implement it in your own repository and share it with the community.

Thanks again
- NGXS Core Team :heart:
