### ISSUE TITLE
🐞[BUG]: states registered with forFeature are not using the right services

### ISSUE THREAD

**Issue by admir86** [ngxs/store#1548]
### Affected Package

The issue is caused by package @ngxs/store

### Is this a regression?

I don't think so

### Description

I have two implementations of an abstract group service. Each of them is registered in a lazy loaded module. (see graphic below).
Also I have a group (shared)state which is using the abstract group service. The state is not abstract and must not be implemented per use case.

When I load the admin module, then the state is using the admin group service, that's ok. But when I switch to the user module the state is still using the admin group service not the user group service.

It looks like the group state instance is the same in each feature module.

![image](https://user-images.githubusercontent.com/36576424/76103209-96248200-5fd1-11ea-8516-0f534ac96b3e.png)

## 🔬 Minimal Reproduction

The [reproduction on stackblitz](https://stackblitz.com/edit/angular-1bejd9?file=src%2Fapp%2Fapp.module.ts) is an implementation of the groups example (graphic).

## Environment

<pre><code>
Libs:
- @angular/core version: 8.2.14
- @ngxs/store version: 3.6.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by arturovt** [comment]
Actually, the current behaviour is expected. Calling `forFeature(sameState)` multiple times is not the same as providing the same service in different modules, which will lead to different instances of this service.

NGXS checks under the hood that the `GroupsState` has been already added to the state graph and skips state initialization if it has.

**Comment by admir86** [comment]
What is the reason for this behavior?
Is there a way to solve this problem with ngxs?

**Comment by arturovt** [comment]
The reason is obvious that is coming from original Redux concepts. The state of your whole application is stored in an object tree within a single **store**. You can't have 10 same states within a single store.

The _most rapid_ way to achieve what you want is just to create 2 classes: `UserManagerGroupsState & AdminManagerGroupsState` and create some base `abstract class` for them, also you will need to have 2 different actions: `LoadUserManagerGroups & LoadAdminManagerGroups`. Treat the state class as a _simple singleton_, it's initialized once and never destroyed (until you do `NgModuleRef.destroy()` or `destroyPlatform()`.

In NGRX you also cannot have `forFeature(featureName)` multiple times with the same `featureName`.
