### ISSUE TITLE
📚[DOCS]: Recipes - Style Guide - Example Code

### ISSUE THREAD

**Issue by HansMusterWhatElse** [ngxs/store#1592]
### Description

Hi guys,

First of all - great job with the NGXS-framework and documentation. I really enjoyed reading through it in my free time.

Just recently I came across this part in the [Style Guide](https://www.ngxs.io/recipes/style-guide#prefer-1) documentation.

Regarding that example code I have a few questions:

- Is there a particular reason that it's adviced to have tiny injectable sub states instead of something like an aggregate root which manages all substates for that particular concern?

- Is there a particular need to have this sub state (e.g GridStateModel) inejctable? Is this needed in order to work with Angular in the first place?

- Is this considered best-practise for NGXS?

Thanks in advance! 

Best Regards
Hans

**Comment by bboydflo** [comment]
@HansMusterWhatElse I am very new to Angular and been using ngxs for a couple of months so I don't have enough experience.

But regarding your question about substates I think it has something to do with how original redux works (combineReducers) where instead of declaring a big, more complicated state slice and reducer, a better approach is to declare small reducers and combine them in the end. it is more manageable. So I think the idea of substates may come from that original redux implementation.

**Comment by HansMusterWhatElse** [comment]
I definitely get that but what would be the whole point of making something like the following injectable?

Wouldn't that be pointless without the proper context? :)

Thanks anways for your response!

```
@State<RowStateModel>({
  name: 'row',
  defaults: {
    id: -1
  }
})
@Injectable()
export class RowState {}
```
