### ISSUE TITLE
🚀[FEATURE]: (Websocket Plugin) Dispatch many Actions

### ISSUE THREAD

**Issue by rjlopezdev** [ngxs/store#1668]
### Relevant Package
This feature request is for __@ngxs/websocket-plugin__

### Description
Websocket Plugin __can't dispatch many deserialized Actions__.

### Describe the problem you are trying to solve
Sometimes, you __can't have control over the server side__.
Currently, the plugin supports `deserializer` option to map incoming payload to an appropiate `Action`.
However, In many ocasions __we need to split that payload in many `Actions`__.

#### Example:

Given the following __`Payload`__:
```json
"data": {
  "message": "Awesome message",
  "timestamp": "2020-09-11T17:42:51+00:00"
}
```

We need dispatch these __`Actions`__:

```typescript
MessageReceived, UpdateLatestIncomingTimestamp
```

### Describe the solution you'd like

`deserialize` option should accept an `Array of Actions` as output & dispatch it in order.

#### Current Signature:

```
deserializer?: (e: MessageEvent) => any;
```

#### Desired Signature:

```
deserializer?: (e: MessageEvent) => any[];
```

or a better __types__:

```
deserializer?: (e: MessageEvent) => MessageEvent[];
```

**Comment by arturovt** [comment]
Thank you for submitting this feature request.
We are closing this issue due to the fact that:
- There has not been much support from other community members

You are welcome to re-open this issue with a further motivation for why this feature is essential for the core library or plugins.
If you would like to pursue the implementation of this feature we would encourage you to implement it in your own repository and share it with the community.

Thanks again
- NGXS Core Team :heart:
