### ISSUE TITLE
🚀[FEATURE]: Inject StateContext additionally to the StateModel into a Selector (Modifable StateModel within Selectors)

### ISSUE THREAD

**Issue by lkaupp** [ngxs/store#1679]
### Relevant Package

 This feature request is for @ngxs/....
@ngxs/store

### Description
 A clear and concise description of the problem or missing capability...
Today, a selector is only used to fetch data. But, i have system, where at runtime the data gets filter. In this case you would use memoised selectors with arguments. https://www.ngxs.io/concepts/select#memoized-selectors-with-arguments

But, i have additional requirements. i want to recognize the parameter calls so that i can return the preprocessed data. If an parameter changes i have to do the preprocessing again and than return the new preprocessed data. At the moment it is impossible to recognize the current calls, because i am unable to patch the current parameters back into the StateModel. Consequently, i had to preprocess my data every time it is requested again. To complicate things even further, i use a joining selector and have to use an additional statemodel to retrieve all the data that i need. The processing takes a while and could be easily avoided or passed if a preprocessed version of the data would exists and if the parameter were not be changed. 

Is it possible to update the state from a selector? If it is not possible, would you think about such a feature? I do not want to preprocess the data each time it is questioned (>100mb)  [do not ask why its a legacy backend].

**Comment by markwhitfeld** [comment]
Hi @lkaupp 
I am really battling to visualize what your problem is. Would it be possible to create a stackblitz to demonstrate the challenge?
There are many different ways to use selectors, but the approach can often depend on the context and may require some trial and error to fit your model (sounds like you are on the error side of that coin at the moment 😉 ).
You can use this as a starting point: https://stackblitz.com/edit/ngxs-repro

**Comment by arturovt** [comment]
Thank you for submitting this feature request.
We are closing this issue due to the fact that:
- This feature is not currently planned for the future
- There has not been much support from other community members
- The use case is not broad enough to be part of the main library
- The proposed feature is not clear enough to be implemented
You are welcome to re-open this issue with a further motivation for why this feature is essential for the core library or plugins.
If you would like to pursue the implementation of this feature we would encourage you to implement it in your own repository and share it with the community.

Thanks again
- NGXS Core Team :heart:
