### ISSUE TITLE
❓[SUPPORT]:  ¿It is a good practice make a dynamic selector?

### ISSUE THREAD

**Issue by wicho1001** [ngxs/store#1680]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

hi, im using selector of ngxs, and our team create a dynamic selector, inside of documentation we didn't see nothing about this, but we´re asking if this is a good practice. Here´s the example of how we doit
`
  @Selector()
  static current_answers(state: QuestionnaireStateModel): {getBy: (questionId: number) => number[]} {
    return {getBy: (questionId: number): number[] => state.userAnswers.filter((a) => a.question === questionId)[0]?.answers || []};
  }
`
and here´s how is consumed in the template 
![Captura de Pantalla 2020-10-02 a la(s) 16 49 27](https://user-images.githubusercontent.com/33376245/94972590-3d698900-04cf-11eb-813e-2388cd488533.png)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by bbarry** [comment]
```typescript
@Selector()
static current_answers(state: QuestionnaireStateModel): {getBy: (questionId: number) => number[]} {
  return {
    getBy: (questionId: number): number[] 
      => state.
        userAnswers.
        filter((a) => a.question === questionId)[0]?.answers || []
  };
}
```

the documentation you are looking for is here: https://github.com/ngxs/store/blob/master/docs/advanced/optimizing-selectors.md#implementation (in the site as well somewhere but ngxs.io is blocked by my employer along with almost every other domain under this hosting provider).

basically this selector implementation is `O(n)` which presumably you are looping over a set of ids and calling it making your component rendering `O(n^2)` which is less than ideal...

You could almost certainly improve the selector like this:

```typescript
@Selector()
static current_answers(state: QuestionnaireStateModel): {getBy: (questionId: number) => number[]} {
  const answersById:number[][] = [];
  state.userAnswers.forEach((a) => {
    answersById[a.question] = a.answers;
  });
  return {
    getBy: (questionId: number): number[] => answersById[questionId] || [];
  };
}
```

This will instead loop once each time the state changes and return an object containing a function that is `O(1)` so your overall complexity is `O(n)` instead of n squared.

**Comment by arturovt** [comment]
@wicho1001  hey, what you're doing is not a selector, you return an object which has a function from a selector, the selector will be re-calculated each time the `QuestionnaireStateModel` changes, but your function will be invoked each time the change detection is run on the component. I wouldn't call it a "dynamic selector" since this is not selector at all.

I would avoid having function in templates (not because I wanna say "hey this is bad for you performance :joy: "), it just makes the code unreadable. What you potentially could have is a pure pipe, that accepts `state` as a parameter (but better `state.userAnswers`, so this requires a selector too) and runs your `filter` function.
