### ISSUE TITLE
🐞[BUG]: No type safety when using @Select decorator

### ISSUE THREAD

**Issue by Grochni** [ngxs/store#1719]
### Is this a regression?
Yes, this used to yield an error in:
- @ngxs/store version: 3.6.2
- @angular/core version: 10.0.2

### Description

There's no longer a type error when using the `@Select` decorator on a property that doesn't match the selector's type.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-jknj2k?file=src/app/app.component.ts
This reproduction works without errors despite the selector's type is string and the property decorated by `@Select` expects a number.

## Environment

<pre><code>
Libs:
- @angular/core version: 11.0.8
- @ngxs/store version: 3.7.1

**Comment by arturovt** [comment]
Hey @Grochni 

Well, the typechecking was removed since that feature also brought a breaking change, where `@Select` decorator couldn't be used with private and protected properties. More info here: https://github.com/ngxs/store/issues/1532 . Everything that brings a breaking change must be reverted, until it's a major release.

There is no possibilty to bring the typeckecking back, at least until NGXS@4 but I'm not sure if this feature is considered for the 4th version.
