### ISSUE TITLE
Lazy load state upon first select: best practice and approach

### ISSUE THREAD

**Issue by fikkatra** [ngxs/store#1787]
Use case: when I select data from the store, I want to lazy load the data if this hasn't been done before. Currently, this is the responsibility of the _consumer_, i.e. the one doing the select. I often see this code turning up:

```
this.store
  .select(TodoState.todos)
  .pipe(
    // check if todos are loaded. If not, load them
    tap((todos) => {
      if (!todos) {
        this.store.dispatch(new TodoActions.LoadTodos());
      }
    }),
    // wait for todos to be loaded
    first((todos) => !!todos),
  )
  .subscribe((todos) => {
    // do stuff with todos
  });
```

This code then gets duplicated in multiple places. I was wondering if there is a better way? Would it be possible, for instance, to create a special kind of `Selector` that dispatches LoadTodos (only when necessary), waits for the dispatch to complete, then returns the data from the state? It feels like going against the redux pattern because it's mixing reads and writes, but it would be so useful.

One other solution I can think of is to create an action _InitTodos_, that loads the todos only if they haven't been loaded before. This would shorten the code to:

```
this.store
  .dispatch(TodoActions.InitTodos)
  .pipe(withLatestFrom(this.store.select(TodoState.todos)))
  .subscribe(([_, todos]) => {
    // do stuff with todos
  });
```

However, it would still be the responsibility of each consumer to dispatch the _InitTodos_ action.

What is the recommended approach to solve this problem?

**Comment by destus90** [comment]
The caching recipe is described in the docs. Have a look at this https://www.ngxs.io/recipes/cache

**Comment by fikkatra** [comment]
Thanks. From the docs I gather that my second example is the recommended approach: the consumer (component) is still responsible to dispatch the action first:

```
this.store
  .dispatch(new TodoActions.InitTodos())
  .pipe(mergeMap(() => this.store.select(TodoState.todos)))
  .subscribe((todos) => {
    // do stuff with todos
  });
```

Of course, the action handler of `InitTodos` will only do an HTTP request if Todos haven't been loaded before.

**Comment by markwhitfeld** [comment]
@fikkatra My recommendation here would actually be to decouple your reads from your writes.

I typically dispatch the init action from a resolver for the route as opposed to in the constructor or init of the component. NB. My resolver function returns `void` (not the observable from the dispatch call) so that it doesn't block the page load.

Your component should subscribe to the `TodoState.todos` observable (in whatever way you prefer) and it should handle the various data returned by the selector accordingly. I often like to represent the different states of my data by adding a bit more details to my selector. Then this can allow for the component to be more resilient and to represent the current state more correctly.

Here are some common states that you would need to deal with: 
- Not loaded
- Loading
- Loaded
- Load error

These can be derived from the data, or can be updated explicitly in your state.

I prefer to have an `OperationStatus` in my state so that I can be explicit about these phases:
```TS
export interface OperationStatus {
  inProgress: boolean;
  success: boolean;
  error: ErrorResult | null;
}

export interface ErrorResult {
  message: string;
  devErrorMessage?: string;
  errorCode?: string;
}
```

In my state I would have a property for this status:
```TS
interface MyStateModel {
  // ...some props
  loading: OperationStatus
}
```
I plan to release an article soon with some helpers that I have written around this pattern.

Hope this helps
