### ISSUE TITLE
❓[SUPPORT]:  Can I use socket.io with websocket-plugin?

### ISSUE THREAD

**Issue by faridg18** [ngxs/store#1794]
I would like to use socket.io in my backend. Is there a way to connect to socket.io with websocket-plugin?

**Comment by arturovt** [comment]
Thank you for submitting this feature request.
We are closing this issue due to the fact that:
- This feature is not currently planned for the future
- There has not been much support from other community members
You are welcome to re-open this issue with a further motivation for why this feature is essential for the core library or plugins.
If you would like to pursue the implementation of this feature we would encourage you to implement it in your own repository and share it with the community.

Thanks again
- NGXS Core Team :heart:
