### ISSUE TITLE
🚀[FEATURE]: Add the option to pass custom comperator function to distinctuntilChanged

### ISSUE THREAD

**Issue by HuiiBuh** [ngxs/store#1826]
### Relevant Package
@ngxs/store

### Description
Sometimes determining if data has changed is not as easy as simply making a shallow compare. For example if you get some updated value from a websocket, save it in the store the selector would emit.
But perhaps the value of the selector has not changed, but because the object you saved in the store, is a new object from the websocket, the reference would not be the same and distinctuntilChanged would not be able to see that in fact nothing changed.

### Describe the problem you are trying to solve
I would like to be able to avoid these unnecessary change detection runs, which are a result by this fact, by being able to pass a custom comperator function, which would for example make a deep equal instead of a shallow one.

### Describe the solution you'd like
Add a new (optional) key to the NgxsModuleOptions which allows me to pass in my custom comperator function.
This function would then be provided to the selector function.
https://github.com/ngxs/store/blob/5b116c155acbc13dcdf4a05d44ae3d3dc64da1c3/packages/store/src/store.ts#L41-L62

**Comment by markwhitfeld** [comment]
The select code does reference equality comparisons by design. 
This is to ensure that your selectors are as performant as possible.

There are 2 approaches to solving your problem:
- [Preferred option] Update only the data that changes in your state. This will result in the selector only firing when there is an actual change and the built-in memoisation will ensure that the selector logic is only run when needed. You can use a state operator like `patch` (and potentially others too) in order to achieve this. `patch` will only update the object in state if there is an actual change.
- Apply your own `distinctUntilChanged` to the observable returned by `store.select`.
