### ISSUE TITLE
🐞[BUG]:  NGXS Forms Plugin - Sub Form with Dynamic Fields - 2 way binding not working. 

### ISSUE THREAD

**Issue by dinbtechit** [ngxs/store#1835]
### Description

I am not sure if this is a bug or if I am doing it wrong. 

NGXS Forms Plugin 2-way binding is not working for subforms with dynamically created fields. Not sure how to transfer the state from `parentFrom` . The fields that are created in the sub form simply overwrites the state to null.

**sub-form.component.ts**
```typescript
  ngOnInit() {
    this.parentForm = this.parentControl.control.get('child');
    // Dynamic Child Field.
    this.parentForm.addControl('childName', new FormControl());
  }
```

![image](https://user-images.githubusercontent.com/17984781/163262321-9ad0b66e-8f7a-4ccb-b31e-8007712c1062.png)

## 🔬 Minimal Reproduction

Take a look at the stackbliz

https://stackblitz.com/edit/ngxs-forms-plugin-simple-example-oyfci1?file=src/app/app.component.ts

## Environment

<pre><code>
Libs:
- @angular/core version: 11.x.x
- @ngxs/store version: 3.7.X
</code> </pre>

**Comment by dinbtechit** [comment]
Any updates on this one?

**Comment by arturovt** [comment]
Sorry for the late response, but I only got my hands on that issue. In your example, the `child` control is added dynamically, meaning it doesn't exist when the form is initialized. The state value gets overridden by `child: {}` and then `child: { childName: null }`. I'm not sure to consider this a bug since the form plugin implementation is supposed to sync the state whenever the `valueChanges` emits and vice versa (sync the form when the state changes).

I don't have deep experience with the form plugin since I don't use it in any app, so I can't advise on the best way to fix it. If you declare `child` control when initializing the form (`child: this.fb.group({ childName: [] })`, then the current state will equal the expected state.

**Comment by dinbtechit** [comment]
No worries. I appreciate the response. But the workaround you proposed is precisely what I am doing right now—initializing all child controls when the form is initialized. 

Although, I think it could be a good feature. If the ngxs-form plugin could dynamically add child controls. Dynamic forms are such a common thing these days.

**Comment by dinbtechit** [comment]
> I ain't sure what you mean by If the ngxs-form plugin could dynamically add child controls

 I meant it would be nice if the plugin could somehow include the state of the dynamically added child controls.

Actually, the code example makes more sense. Thank you. I appreciate it.
