### ISSUE TITLE
Warning message in unit tests

### ISSUE THREAD

**Issue by Keehlx** [ngxs/store#1837]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
In Angular 13 there is annoying warning message in unit tests:
'RECOMMENDATION: Set developmentMode to true on the NgxsModule when Angular is running in development mode.
NgxsModule.forRoot(states, { developmentMode: !environment.production })'

## Environment

<pre><code>
Libs:
- @angular/core version: 13.3.3
- @ngxs/store version: 3.7.3

For Tooling issues:
- Node version: 12.22.10
- Platform:  Windows

**Comment by arturovt** [comment]
Hey @Keehlx . I know this is an issue and that's really annoying. We're deprecating the `developmentMode` option (https://github.com/ngxs/store/commit/d470dff03488df9b5de3f0e5f9acfa2dcf33da3c#diff-e5db104e9cc41451a3498a985e322b92568b135072c61500e9fe7957fe697b13R34-R35) and will be able to determine if Angular is running in development mode or not through `ngDevMode` definition (which is provided by Angular itself).

But since that's a breaking change we'll be able to ship it only in v4.

**Comment by arturovt** [comment]
UPD we actually removed this warning in 3.7.4.
