### ISSUE TITLE
🐞[BUG]: Synchronous action dispatch does not behave the same way inside action handler

### ISSUE THREAD

**Issue by DCollart** [ngxs/store#1860]
### Affected Package
@ngxs/store

### Is this a regression?
No

### Description
I have 2 synchronous actions with a (disgusting) sleep.
If I dispatch those two actions (one action by "dispatch" call) in a component I can clearly see they are executed in the right order.
The first action is handled then only the second action is handled.

If instead to have 2 "dispatch" call in my component I decide to let the first action handler to dispatch the second action (first line of the handler) the second action is only handled when the first action is completed.

I don't know if it's "by design" but I think if the exact same line of code give different result it can be an issue... 

I read the documentation about the action lifecycle but I don't see any mention of a "queue" or a delayed synchronous action?

## 🔬 Minimal Reproduction

This is an example with 2 dispatch at the component level:
https://stackblitz.com/edit/ngxs-repro-vxtopr

This is an example with one dispatch inside another action handler:
https://stackblitz.com/edit/ngxs-repro-czgvpq

I know I could have used the "context" to dispatch the action from the action handler but I wanted the exact same line of code than in the previous example.

You can check the console. In both cases you have the same result (action 1 then action 2) but I would expect to see the action 2 handled before the action 1 in the second case.

**Comment by arturovt** [comment]
The current behavior is by design. Synchronous actions are handled in the order they’re dispatched, meaning that “DoNothing2” is put onto the queue. Otherwise, that would’ve lead to an inconsistent behavior with synchronous actions when they would go out of order. For better understanding, you can look at the “OrderedSubject” we have in our codebase and unit tests for this subject. Asynchronous action order would depend on how you dispatch an action (whether you wait or not). Given that “DoNothing2” awaits the timer, you could dispatch this action within the “DoNothing1” and call “await” or forget. Logs would be different.
