### ISSUE TITLE
Parameters in Memoized Selectors

### ISSUE THREAD

**Issue by piernik** [ngxs/store#195]
### Versions

```
* ngxs: 2.0.0
* @angular/core: 5.2.6
```

We can build Memoized Selectors:
```
@Selector()
static table(state: any) {
    return state.myTable.fields;
}

@Select(State.table) fields$;
```
Is there an option to add parameter to selector? 
```
@Selector()
static table(state: any, params:any) {
    return state[params].fields;
}

@Select(State.table, 'table') fields$;
```

**Comment by mailok** [comment]
@piernik It looks very interesting to be able to do that!

**Comment by deebloo** [comment]
just curious. what happens if you do the following?

```TS
@Selector()
static table(myArg) {
    return function (state: any) {
      return state[myArg].fields;
    };
}

@Select(State.table('something')) fields$;
```

**Comment by mailok** [comment]
@deebloo i test that and give me a error

**Comment by estrellajm** [comment]
@deebloo I tried your solution, but I get an error as well:

@leon this is the feature that I was looking for, which doesn't seem to work. 

Please advise

```
core.js:1664 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'split' of null
TypeError: Cannot read property 'split' of null
    at getValue (ngxs-store.js:173)
    at Function.fn_1 (ngxs-store.js:821)
    at Function.memoized (ngxs-store.js:804)
    at eval (company.component.ts:63)
    at eval (company.component.ts:77)
    at Object../src/app/main/pages/company/company/company.component.ts (company.module.chunk.js:133)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (company.module.ts:13)
    at Object../src/app/main/pages/company/company.module.ts (company.module.chunk.js:111)
    at __webpack_require__ (inline.bundle.js:55)
    at getValue (ngxs-store.js:173)
    at Function.fn_1 (ngxs-store.js:821)
    at Function.memoized (ngxs-store.js:804)
    at eval (company.component.ts:63)
    at eval (company.component.ts:77)
    at Object../src/app/main/pages/company/company/company.component.ts (company.module.chunk.js:133)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (company.module.ts:13)
    at Object../src/app/main/pages/company/company.module.ts (company.module.chunk.js:111)
    at __webpack_require__ (inline.bundle.js:55)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at eval (zone.js:873)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4956)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
```

**Comment by juliusstoerrle** [comment]
@estrellajm can you add your code, I think your problem is a null pointer exception to the object you try to select, which isn't in store and not directly how the function is set up.

**Comment by estrellajm** [comment]
@deebloo please reference the github project
https://github.com/estrellajm/itinerary

Origin path: 
`src/app/modules/core/components/sidenav/sidenav.component.ts`

State path: 
`src/app/modules/core/state/layout.state.ts`

I've commented out lines 22 & 23 in sidenav.component.ts

22 gives me the error.

Thanks in advnace

**Comment by estrellajm** [comment]
@deebloo Please let me know if you have VS Code and want to do VS Live Share

**Comment by estrellajm** [comment]
@deebloo @amcdnl  BTW, I've been trying to use the dot notation path as a temp fix to select the slice of the state that I'm looking for but it errors out after 4 parameters. This only works up to 

`@Select(state => state.user.locations.new_york) apartments$;`

but the full path that I was trying to query is

`@Select(state => state.user.locations.new_york.sites.42broadway.apartments) apartments$;`

OR

`@Select(state => state.user.locations.[site.id].sites.[site.location].apartments) apartments$;`
FYI, the above does not work. @Select does not seem to like syntax '[site.id]'. I tried prepping the string entirly before as well, but no luck.

# GOAL:
Frankly, I'm hoping to just call the following @Selector
```
@Selector()
static getApartments(state: UserState, site: any) {
  return state.user.locations.[site.location].sites.[site.address].apartments
}
```

so that in my `components.ts` I could just use 
```
site = {
  id: 'new_york',
  address: '42broadway'
}
@Select(UserState.getApartments(site)) apartments$
```
# SUCCESS!

I was finally able to get the deeply nested object that I was looking for, but it was in a very hacky way.

I first sliced as deep as I could
```
site = {
  id: 'new_york',
  address: '42broadway'
}
@Select(state => state.user.locations) tmp_apartments$;
```

then I had to 'map' the rest of the way guarding and fighting against that deceitful `'undefined'`:

```
    this.apartment$ = this.tmp_apartment$.pipe(
      map(a => {
        if (typeof a !== 'undefined') {
          const b = a[this.site.id];
          if (typeof b !== 'undefined') {
            const c = b['locations'];
            if (typeof c !== 'undefined') {
              const d = c[this.site.location];
              if (typeof d !== 'undefined') {
                const e = d['address'];
                if (typeof e !== 'undefined') {
                  const f = Object.keys(e).map(id => e[id]);
                  return f;
                }
              }
            }
          }
        }
      })
    );
```
Ultimately, this allows me to pass in my parameters, such as site.id or site.address. Then, I can successfully use `apartments$` anywhere I'd like

### Please forgive the untrained mind...

**Comment by amcdnl** [comment]
I don't believe this is a issue with NGXS given your response.

**Comment by piernik** [comment]
@amcdnl it was na feature request - why did You closed it?

**Comment by amcdnl** [comment]
This is a language thing. There is nothing I can do here for you.

**Comment by estrellajm** [comment]
@amcdnl, can you explain how this is not a NGXS issue? I tried providing as much data as possible. Not sure how this is a language thing. The specific example below illustrates that it could be a NGXS issue, due to the fact that I can only go so deep:

#This works:
`@Select(state => state.user.locations.new_york) apartments$;`

#This doesn't work:
`@Select(state => state.user.locations.new_york.sites.42broadway.apartments) apartments$;`

Please advise

**Comment by piernik** [comment]
@amcdnl 
Using multiple params in decorator is not possible in typescript?
```
@Select(State.table, 'table') fields$;

@Selector()
static table(state: any, params:any) {
    return state[params].fields;
}
```
How about using object (as alternative)?
```
@Select({state: State.table, params:{table:'table'}}) fields$;

@Selector()
static table(state: any, params:any) {
    return state[params.table].fields;
}
```

**Comment by markwhitfeld** [comment]
@piernik I have good news for you.
I think that I have an approach that will sole your problem. 
See this comment here: https://github.com/ngxs/store/issues/386#issuecomment-390181710 
This is part of a discussion around selectors so please feel free to add your votes.
