### ISSUE TITLE
moving to ngxs from ngrx

### ISSUE THREAD

**Issue by bartes** [ngxs/store#219]
hi @amcdnl, 

I've got few rather general questions about moving from ngrx to ngxs

- do you know is there a guide/resource somewhere how to quickly move to ngxs from ngrx? 
- are there any generators which could extend  something like angular-cli generators with ngxs elements?
- for larger apps is there a way to make it work with ngrx side by side till full conversion?
- do you have some team behind you or are you the only maintainer here ? :)

and BTW amazing job 👍

**Comment by amcdnl** [comment]
1) Not at the moment. Personally, I avoid comparing it because there are quite a bit of differences.
2) There is a GH issue for schematics and someone mentioned taking it on but not at the moment. I also know that NG6 CLI is dramatically different so its probably best to wait til that is stabilized.
3) I'm sure you could run them side by side, not sure what that would look like though. If you broke it down by feature area, it would probably be easier instead of trying to mimic both states in both systems.
4) I'm the main author but the community has came together and contributed quite a bit! Big shout to @deebloo @leon for their work! We wouldn't be here without their ideas and contributions!

Thanks so much!
