### ISSUE TITLE
❓[SUPPORT]: Performance question about select/selectSignal

### ISSUE THREAD

**Issue by XavierDupessey** [ngxs/store#2214]
Hi there,

I noticed that NGXS 18 now supports the Signal API, which is exciting! I have a question regarding the performance of the `selectSignal` function.

Using the code example below, are there any performance optimizations that signals offer compared to a custom (simple) `selectValue` function?

```typescript
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  DestroyRef,
  inject,
} from "@angular/core";
import { SampleStateSelectors } from "./sample-state/sample-state.selectors";
import { select, Store, TypedSelector } from "@ngxs/store";
import { takeUntilDestroyed } from "@angular/core/rxjs-interop";

export const selectValue = <T>(selector: TypedSelector<T>): (() => T) => {
  const changeDetectorRef = inject(ChangeDetectorRef);
  const destroyRef = inject(DestroyRef);
  const store = inject(Store);

  let value = undefined;

  store
    .select(selector)
    .pipe(takeUntilDestroyed(destroyRef))
    .subscribe((nextValue) => {
      if (nextValue === value) {
        return;
      }

      value = nextValue;
      changeDetectorRef.markForCheck();
    });

  return () => value;
};

@Component({
  selector: "sample-component",
  template: `
    <p>Signal: {{ ageSignal() }}</p>
    <p>Function: {{ ageFn() }}</p>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
})
export class SampleComponent {
  readonly ageSignal = select(SampleStateSelectors.age);
  readonly ageFn = selectValue(SampleStateSelectors.age);
}
```

I recognize that signals provide additional capabilities, such as integration with `computed` and `effect`. My focus, however, isn't on comparing features but purely on performance.

Thanks!

**Comment by markwhitfeld** [comment]
Hi @XavierDupessey 
The `selectValue` function that you have implemented is logically equivalent to the `toSignal` function offered by angular from the `@angular/core/rxjs-interop` sub-package of  `@angular/core` ([docs](https://angular.dev/guide/signals/rxjs-interop#tosignal), [source](https://github.com/angular/angular/blob/8da9fb49b54e50de2d028691f73fb773def62ecd/packages/core/rxjs-interop/src/to_signal.ts#L133)).

The advantage of using the built in `select` (or `store.selectSignal`) from NGXS is that:
1) It runs the memoised selectors only when the value is requested.
  - From a performance point of view, this means that multiple changes to state that affects the current selector within a single change detection cycle will result in only a single request of the value from the selectors. At a fundamental level, signals are naturally debounced to the change detection cycle. 
  - In short, observables call selectors whenever the state changes, but the NGXS signal calls selectors when the signal is read by the component (the first time, and only in the change detection cycle following a state change).
  - The final value of the signal is memoised by angular, so that means that Angular has the opportunity to optimise the re-read of this value.
  - There are also other future performance improvements around the signals pipeline within NGXS that will make this even more performant.
  - I have built a StackBlitz example showing off the difference in selector recalculations. Clicking `+5` runs 5 actions in a row. You will see the difference in number of selector recalculations: https://stackblitz.com/edit/ngxs-18-signals-perf?file=src%2Fmain.ts
2)  If you don't use the NGXS signal, you will have issues if you dispatch an action from within an `effect`. This would need to be manually resolved by wrapping the dispatch in an `untracked` call to fix the problem. This is not necessary if you use the built in NGXS signal.

**Comment by XavierDupessey** [comment]
Thank you for your response and the StackBlitz example, it's really interesting! It's good to know that using `selectSignal` benefits from internal optimizations.

Your sample code with `computed()` raises another question for me. The `isOdd`, `isEven`, and `fullCups` logic could also be implemented using selectors. Now that Angular provides the `computed` function, I imagine developers might be unsure which approach to choose. Do you have a recommendation?
