### ISSUE TITLE
Dispatch observable not firing in particular scenarios

### ISSUE THREAD

**Issue by markwhitfeld** [ngxs/store#233]
### Versions

```
* ngxs: 3.0.0-beta.0
* @angular/core: 5.0.0
```

### Repro steps

I have picked up some issues with the dispatch method observable. 
The observer does not ever get hit in these situations:
- when the action handler returns something other than a void/promise/observable
- when there aren't any action handlers for the Action

Do you agree that the observable should still publish completion in both of these scenarios?

**Comment by leon** [comment]
### when the action handler returns something other than a void/promise/observable
It seems that we don't complete if we return something other than undefined. see:
https://github.com/ngxs/store/blob/master/packages/store/src/state-factory.ts#L114

@amcdnl removed the possibility to return anything but a Promise or Observable a while back as to not confuse people. you should use the `StateContext.dispatch` method if you want to dispatch something, but then you should not return anything from the action.

I think we should either change the be so that behaviour is consistent where you will get what you returned from the action, even if it's not a promise or observable.

```TS
let result = metadata.instance[actionMeta.fn](stateContext, action);

if (result instanceof Promise) {
  result = fromPromise(result);
} else {
  result = of(result).pipe(shareReplay());
}

if (result instanceof Observable) {
  result = result.pipe(
    (<ActionOptions>actionMeta.options).cancelUncompleted
      ? takeUntil(actions$.pipe(ofAction(action.constructor)))
      : map(r => r)
  ); // act like a noop
  results.push(result);
}
``` 

Or we need to throw an error saying that an action that does not return a promise or observable needs to return void.

I think we should go with the first option of having an action that you subscribe to always be converted into an observable with the result of the action.

**Comment by markwhitfeld** [comment]
@leon Submitted my PR. 
I added the missing dispatch method tests, reproduced with tests, and fixed this.
Submitted this before I read your message above and I had chosen to go with the option of always converting to an observable. Made sense to me.

**Comment by markwhitfeld** [comment]
@leon The only digression in my PR from what you mentioned here is that if a primitive is returned then the result is ignored and an Observable.of({}) is returned. The result in the observable is ignored anyway and replaced with the latest state. 
Would you like me to make the change so that the primitive result is wrapped in an Observable as you suggested. (This code doesn't need to know that this result is not used)
