### ISSUE TITLE
Action Handler not getting executed. 

### ISSUE THREAD

**Issue by xmlking** [ngxs/store#239]
### Versions

```
* ngxs: 3.0.0-dev.bcbc16f
* @angular/core:  6.0.0-rc.3
```

### Repro steps

* Step 1
Added Injectable https://github.com/xmlking/nx-starter-kit/blob/master/apps/default/src/app/core/state/eventbus.ts
* Step 2
imported into Angular Module https://github.com/xmlking/nx-starter-kit/blob/master/apps/default/src/app/core/core.module.ts#L45
* Step 3
login to trigger "Login" action
https://xmlking.github.io/nx-starter-kit/index.html

### Observed behavior
no "New Login!......."  log message printed  
 
### Desired behavior
expected to see "New Login!......." log in the console.

### Mention any other details that might be useful (optional)

https://xmlking.github.io/nx-starter-kit/index.html

**Comment by critchie** [comment]
I'm having similar difficulties with action handlers.  It seems it is not enough to just create the action handler and install it into the providers collection.  You actually have to inject the action handler into something so it will be instantiated at least once by DI.

So I think the question here is... How does the action handler injectable get picked up by the system?  It has to be injected into something at least once to get instantiated by DI.  I put it on my constructor of my State class.  Not sure if this is "correct" but it is working.

The action handler documentation needs to be enhanced telling us just how the injectable action handler is plugged into the system.

**Comment by yarrgh** [comment]
In order for it to be created by angular, you have to inject it somewhere, not just add it to the providers. Doesn't matter where it is injected or if you use it. 

May be better to add it to `foorRoot()` and `forFeature()`?

**Comment by critchie** [comment]
"May be better to add it to foorRoot() and forFeature()?"

I was thinking the same thing.  What I did to get it to work feels like a hack.

Maybe another parameter on the current forRoot or forFeature that takes an array of action handler types.

`NgxsModule.forRoot([], [RouteHandler])`

Since these feel like effects maybe a ActionHandlerModule with a forRoot/forFeature that takes an array of action handler types.  But this feels like overkill as there is no real need for a ActionHandlerModule.

`NgxsActionHandlerModule.forRoot([RouteHandler])`

**Comment by amcdnl** [comment]
Odd....I'm using this a lot and not had this issue.

**Comment by critchie** [comment]
amcdnl,

Can you share how you set your action handler?  Maybe you dug some secret nugget out of the documents that I'm missing.

**Comment by amcdnl** [comment]
Here is my usage - https://www.screencast.com/t/z04ak0T0fPJE

**Comment by critchie** [comment]
Thanks for the example.  You are taking the second approach the [documentation] (https://ngxs.gitbook.io/ngxs/advanced/action-handlers) is showing.  But if you follow the first example of putting action listeners in an Injectable class, that injectable class has to be injected somewhere before the constructor will run and start listening for actions.

I switched over to the second approach of putting my action listeners on the component itself like your example.

**Comment by yarrgh** [comment]
Unless it is the AppComonent, components can be destroyed and recreated as you navigate around and having it in a component can cause multiple subscriptions (unless you make sure to unsubscribe when the component is destroyed). 

I didn't want to deal with that so I've been placing them in the state which, I know, is not desired and violates the reason they were introduced or I've just been injecting the action handler into my state and doing nothing with it.

**Comment by yarrgh** [comment]
I have to possible improve the second approach in the docs. I think it could/should be done using the `Store`.

Something like this:
```ts
@Component({ ... })
export class CartComponent {
  constructor(private store: Store) {}
 
  ngOnInit() {
    this.store.action<CartDeleteSucess>().subscribe(() => alert('Item deleted"));
  }
}
```

This would take care of running `this.actions$.pipe(ofAction(CartDeleteSuccess))` and return the observable.

**Comment by yarrgh** [comment]
I agree. Neither are desirable. I like the approach you suggested. Either have another module (`NgxsActionHandlerModule`) to import and create the action handlers, or allow for another parameter in `NgxsModule.forRoot()` and `NgxsModule.forFeature()` to allow us to pass in action handlers.

**Comment by leon** [comment]
I've talked to Austin about it and we haven't really figured out how our version of ngrx`@Effects` will look like.

But I did come up with a good way to initialize services by using `APP_INITIALIZER`.

I've created a demo for you, and until we figure out how to best tackle the action handlers, you will have to include your own HandlerModule.

https://stackblitz.com/edit/ngxs-action-handlers?file=app%2Fhandler.module.ts

Open the console and you should see how all the stuff gets initialized properly.

I'm going to close this issue now, since we have found a solution to the problem.
But keep your eyes open and we might find a better solution later on.

**Comment by amcdnl** [comment]
@leon - Can you add this to the docs?

**Comment by FortinFred** [comment]
I have tried the APP_INITIALIZER approach and I'm getting "annot instantiate cyclic dependency! ApplicationRef" Error when my handler is injecting "Router".

**Comment by yarrgh** [comment]
The router can't be injected correctly into your handler. Inject `Injector`. And then right before you need the router, use the `Injector` to inject the router.

**Comment by stoubia** [comment]
This is great to come across, because I'm a bit new to angular and the docs still show that you inject Router into the handler.  Very frustrating.
