### ISSUE TITLE
Type Safety

### ISSUE THREAD

**Issue by deebloo** [ngxs/store#25]
There are several parts of the library that open the user up to potential mistakes that SHOULD be caught by the compiler. An example of this is the Select decorator and the fact that the Ngxs class isn't generic so the select method cannot be typed. Anything where you pass in a string (like the selectors) are an opening for potential mistakes

**Comment by amcdnl** [comment]
See this for types on decorators: https://github.com/Microsoft/TypeScript/issues/4881

**Comment by deebloo** [comment]
I think there are some other small things that can be done as well. There are to many methods and functions that accept "any" and return "any"

**Comment by amcdnl** [comment]
Yes.

**Comment by deebloo** [comment]
@amcdnl I am going to close this and just count on it as an ongoing effort

**Comment by IlCallo** [comment]
I understand the problems with Decorators, but with the normal API on the `Store` service?

Every time I do a

    this.store.selectSnapshot(SomeState.selector)

then I'm forced to explicitly type the return value because it returns `any`.
I'm not a super-expert, and I surely didn't dig enough in this library code, but isn't it possible to allow inference from the selector return type?

Like an additional method overload which get the generic function and returns the same return type.
Something like

```typescript
selectSnapshot<R>((state: any) => R): R
```
