### ISSUE TITLE
TypeError: Object(...) is not a function 

### ISSUE THREAD

**Issue by anakinjay** [ngxs/store#267]
### Versions

```
* ngxs: 3.0.0-dev.b16978b
* @angular/core: 5.2.0
```

### Repro steps

I tried following the documentation, and got this error.   So assuming I was doing something wrong, I started following this tutorial and got the same result:
https://coursetro.com/posts/code/152/Angular-NGXS-Tutorial---An-Alternative-to-Ngrx-for-State-Management

### Observed behavior
TypeError: Object(...) is not a function
    at StateFactory.invokeActions (ngxs-store.js:357)
    at eval (ngxs-store.js:518)
    at eval (ngxs-store.js:407)
    at Store._dispatch (ngxs-store.js:528)
    at Store.dispatch (ngxs-store.js:474)
    at new NgxsRootModule (ngxs-store.js:622)
    at _createClass (core.js:10901)
    at _createProviderInstance$1 (core.js:10865)
    at initNgModule (core.js:10818)
    at new NgModuleRef_ (core.js:12073)
```
<!-- Normally this includes a stack trace and some more information. -->
```

### Desired behavior
should not error

### Mention any other details that might be useful (optional)
It references main.ts line 12 which is the app module bootstrap.

**Comment by deebloo** [comment]
@anakinjay can you share the code that got you this error?

**Comment by anakinjay** [comment]
Sure thing:

https://github.com/anakinjay/type-error-ngxs

**Comment by anakinjay** [comment]
alright good to go, had to actually commit the ngxs files haha.

**Comment by killbox-code** [comment]
I'm getting this now as well after moving from 2.1.0-beta.9 to 3.0.0-rc.0. 3.0.0-dev.b16978b produces the same error. Appears to be an adverse side-effect of [this change](https://github.com/ngxs/store/commit/bcbc16ffd7e6d773ff4135bc283fbcc840ca7d0b) - state-factory line:133 is who the stack trace blames:
```typescript
results.push(of({}));
```

**Comment by deebloo** [comment]
@killbox-code yup saw that. it isn't failing in our integration app so im trying to see what is happening

**Comment by deebloo** [comment]
@anakinjay I just looked at your project and it looks like you were using the wrong version of rxjs and angular. 3.0 includes angular 6 and rxjs 6 support. you will either need to upgrade to the latest rx or include rx-compat. can you give that a try and see if it works?

**Comment by manjureddy7** [comment]
@anakinjay I got the same Error. with the same setup and same Documentation.

**Comment by manjureddy7** [comment]
So Cant we use NGXS with old version of Angular? @deebloo

**Comment by manjureddy7** [comment]
Issue solved by downgrading ngxs/store to 2.1.0-beta.9. Everything working fine now

**Comment by killbox-code** [comment]
@deebloo -
Like @manjureddy7, when I downgrade to 2.1.0-beta.9 everything functions as desired. I see what you're saying that 3.0.0-rc.0 supports the newest angular & rxjs versions, I think the issue here is that 3.0.0-rc.0 is 'latest' from NPM, and as such may present these issues to anyone seeking to use it with 'latest' of angular and rxjs. Perhaps @ngxs/* v3.0.0+ should be in the @dev or @next branch?

Also, with 3.0.0-rc.0, I had the same issue described in [#264](https://github.com/ngxs/store/issues/264), as the interface it's complaining about is not exposed in rxjs5.5.9 when importing the way it was, whereas rxjs/compat has it reachable via 'rxjs' or 'rxjs/Rx'.

Shame on me for getting a this far without saying the obvious... THANK YOU for your work. Honestly Sir, @ngxs/store is a game changer for angular state management and it has been very refreshing to finally feel like I'm managing state 'the angular way'.

**Comment by amcdnl** [comment]
@manjureddy7 - You can use it w/ old version of angular but you must upgrade RX to 5.5.6-foward-compat or RX6
