### ISSUE TITLE
Discussion - Experiment: Converting ngrx app to ngxs

### ISSUE THREAD

**Issue by juristr** [ngxs/store#317]
Hey, as said in the chat, this is not an issue, but rather some open points I encountered during an experiment of converting an ngrx app to ngxs.

The sample repo is here: https://github.com/juristr/ngxs-tests. It's basically Todd Motto's NGRX app from his course converted to NGXS.

### Reusing of selectors

This has been briefly discussed in the Slack chat already. Basically I want to have a selector that aggregates the current `Pizza` (in the `PizzaState`) with the selected toppings (in the `ToppingsState`). Currently I use a selector in the parent state `ProductsState` as follows: https://github.com/juristr/ngxs-tests/blob/ngxs-01/src/app/products/store/state/products.state.ts#L30-L44  

The strange thing here is that in the `ProductsState` I cannot easily reuse the `ToppingsState.getSelectedToppingsEntities` which is defined already in the `ToppingsState`. Uncommenting [this line](https://github.com/juristr/ngxs-tests/blob/ngxs-01/src/app/products/store/state/products.state.ts#L33) doesn't work, even if the types are properly casted, the UI doesn't update any more. On the other side, if I duplicate the behavior [like here](https://github.com/juristr/ngxs-tests/blob/ngxs-01/src/app/products/store/state/products.state.ts#L34-L36) then it works.

### Observable fires multiple times? 🤔

In the `product-item.component` I have defined my selector here: https://github.com/juristr/ngxs-tests/blob/ngxs-01/src/app/products/containers/product-item/product-item.component.ts#L71-L73

That works, but rather I'd like to reuse the one defined in the `ToppingsState.getAllToppings` and reference it using the `@Select(..)` decorator, such as [in this commented part here](https://github.com/juristr/ngxs-tests/blob/ngxs-01/src/app/products/containers/product-item/product-item.component.ts#L71-L73). However, that somehow causes multiple firings of the observable (apparently if I got that properly). The `toppings$` bound to [`pizza-form`](https://github.com/juristr/ngxs-tests/blob/ngxs-01/src/app/products/components/pizza-form/pizza-form.component.ts#L94) updates multiple times when clicking on toppings in the detail of a pizza causing multiple `ngOnChanges` calls [here](https://github.com/juristr/ngxs-tests/blob/ngxs-01/src/app/products/components/pizza-form/pizza-form.component.ts#L117). As a result, the UI doesn't work properly.

On the other side, not using the `@Select` decorator and reselecting with `this.store.select(...)` works just fine.

---

I know this is probably kind of complicated to understand here 😅. Happy to jump into a hangouts call in case

**Comment by markwhitfeld** [comment]
Hi @juristr 
See the discussion here regarding the Reusing of Selectors: https://github.com/ngxs/store/issues/386

**Comment by juristr** [comment]
@markwhitfeld thx, need to check it out

**Comment by alterx** [comment]
Hey, @jurist , for the first question you just need to provide `state.toppings` since the selector [here](https://github.com/juristr/ngxs-tests/blob/aeda5564769ec5e2201be1973e61e80f50e8b55c/src/app/products/store/state/toppings.state.ts#L39) is expecting a `ToppingsStateModel` type:

```
static getAllToppings(state: ToppingsStateModel) {
    return Object.keys(state.entities).map(id => state.entities[+id]);
  }
```
So, doing `const toppings = ToppingsState.getSelectedToppingsEntities(state.toppings);` should work.

The second issue is a bit trickier, I also stumbled upon it while moving the Angular Ultimate NGRX/store code to ngxs. Has there been any change in this?

Using the `@Select` decorator works but I'd prefer reusing the existing selector.

**Comment by juristr** [comment]
@alterx I ended up being able to do it somehow, but with "workarounds". Didn't continue this experiment due to other stuff I had to do first. But afaik meanwhile the latest NGXS version has a way to reuse selectors more easily, which should help here.

I plan to continue my experiment & will let you know if I make any progress. Will take some time though, as I have other stuff to complete first 🙄

**Comment by alterx** [comment]
Yeah, I'm using `ngxs` for a project and I've had to use a couple of workarounds too (like using `store.select(...` but just wanted to reach out and see if, maybe, there's been some changes on this

**Comment by alterx** [comment]
Well, I had some free time to look into this and it turns out the error was, indeed, in the ng-pizza code.
This commit fixes it:
https://github.com/alterx/ng-pizza-ngxs-ngrx/commit/2d59a9fe93dce86ab7dcae6dfbb32df343a48a92

It basically uses the pizza from the `changes` object instead of the one from the input. This avoids the pizza being reset to the initial value every time. In addition, the subscribe was being called every time we had a change (every time a topping is selected) so I moved it inside the if statement. This if statement is only true the first time it loads a pizza, after that it will just be skipped.

**Comment by alterx** [comment]
Just to add to this, the main issue that caused this problem is a different behavior when creating the selectors. Now I'm not an expert in the inner works of neither lib but I created a small example that depicts the issue for a simple case: https://stackblitz.com/edit/angular-ngchanges-ngxs-ngrx

If you look at line 47 [here](https://stackblitz.com/edit/angular-ngchanges-ngxs-ngrx?file=src%2Fapp%2Fngrx%2Fngrx.duck.ts) you'll see that I'm creating a bunch of selectors that, ultimately, give me an array of elements (out of the entities object). If you click the 'Get random name' button in the ngrx component and look at the console you'll see that there are no subsequent `onChange` events. On the other hand, line 32 [here](https://stackblitz.com/edit/angular-ngchanges-ngxs-ngrx?file=src%2Fapp%2Fngxs%2Fngxs.state.ts) achieves the same purpose of creating the array of elements out of the entities object, this time for **ngxs**.

If you click the 'Get random name' button in the **ngxs** component, you'll see that a bunch of `OnChange` events are fired even though the `name` property isn't part of the selector. In fact, it is not even being sent down as an `@Input` for the [child component](https://stackblitz.com/edit/angular-ngchanges-ngxs-ngrx?file=src%2Fapp%2Fchild.component.ts).

From what I can see this is an issue related to how selectors are created/treated/memoized between the two libs. It looks like `ngrx` doesn't trigger unnecessary `OnChange` events while `ngxs` doesn't. Is this related to the #386 discussion at all? Is this a bug or are you guys aware of this behavior?

cc. @markwhitfeld , @amcdnl

**Comment by ahnpnl** [comment]
hi, I have a question regarding to a part of this topic. I want to convert an Effect class of `ngrx` to `ngxs` way. What is the recommendation for this case ? I'd love to create something similar to `ngrx` Effect for handling side effects of my actions in `ngxs`. Actually I can subscribe to the action stream and call a method to create the subscription but I think something like `ngrx` Effect decorator is better.

**Comment by markwhitfeld** [comment]
@ahnpnl I have thought for a while that it could be a good ngxs-labs project to create an Ngrx conversion utilities library. Would you like to have a go at creating a utilities library that you think would be useful to help with converting an Ngrx library to Ngxs? This could be created as a library separate to the core @ngxs/store library. If you want to have a go at this please let me know ;-)

**Comment by splincode** [comment]
We started work so that similar decorators could be used on NGRX.
https://github.com/ngrx-labs/state

**Comment by splincode** [comment]
https://medium.com/@joshblf/migrating-from-ngrx-to-ngxs-in-angular-6-ddddcdce543e
