### ISSUE TITLE
Apollo cache support

### ISSUE THREAD

**Issue by bmayen** [ngxs/store#380]
When using Apollo with ngrx we can use the following to integrated the Apollo cache with our ngrx store:
https://github.com/apollographql/apollo-angular/tree/master/packages/apollo-angular-cache-ngrx.
Without this integration, Apollo will default to inMemory cache. While this won't necessarily break our app, it does create two separate sources of truth which can eventually lead to problems. Would be nice to have apollo-angular-cache-ngxs to address this.

**Comment by thefliik** [comment]
So this is probably just a semantic difference, but I'm pretty sure that, even using apollo-angular-cache-ngrx, Apollo *still* uses the inMemory cache to save/access/manipulate its data.

Having used the apollo-angular-cache a (small) bit, I think that all the it does watch Apollo's cache and copy changes into the NGRX store (and, I imagine, changes you make to the `apolloReducer` trigger updates to the Apollo inMemory cache--though I haven't tested this). i.e. there are still two different stores. This distinction probably doesn't matter for your use case, but it contrasts with other apollo store integrations like [Hermes](https://github.com/convoyinc/apollo-cache-hermes) which actually ***do*** replace the default inMemory cache with a new caching mechanism.

Personally, the problem I encountered with the apollo-angular-cache integration was that the flat format apollo uses to save its data in (which apollo-angular-cache doesn't appear to alter in any way) makes it pretty difficult to access/read from (I found I'd need to basically replicate a lot of the logic that apollo has to rebuild my graph structure, which begged the question of why I didn't just use apollo directly...).

**Comment by bmayen** [comment]
I don't actually have much hands on experience with this. Getting ready to use Apollo with an existing project that uses ngrx. But I'm keen to use ngxs in my next project and thought this would be helpful. I'll have some more feedback on this once this current project wraps.

**Comment by thefliik** [comment]
Ya, I wanted to comment because, with my limited experience using `apollo-angular-cache-ngrx`, I'm not sure how useful it is (I'd be interested to hear from someone who uses it successfully). The problem is that it doesn't seem to alter Apollo's caching mechanism/structure in any way, and so it saves data to your store as a flattened object.

Ngrx isn't set up to retrieve flat data and so, in my experience, it was incredibly difficult to make use of the apolloReducer data inside ngrx. As an example, say you have a graph schema like this pseudo-code
```
person {
  firstName

  addresses {
    edges {
      node {
        street
        city
      }
    }
  }
}
```
Which returns JSON like ~
```
"person": {
  "firstName": "thefliik",

  "addresses": {
    "edges": [
      {
        "node": {
          "street": "123 Awesome Street",
          "city": "Awesome City"
        }
      },
      {
        "node": {
          "street": "4 OK Street",
          "city": "Awesome City"
        }
      },
      {
        "node": {
          "street": null,
          "city": "Town Place"
        }
      }
    ]
  }
}
```
It's saved to the apolloReducer in your store like:
```
{
  "$23298472398unkjdnfasd-person.uuid": {
    firstName: "thefleek",
    addresses: "$12390898sdf987498234dkjahfd-person-addresses-connection-object",
    apolloMetadata: {}
  },
  "$12390898sdf987498234dkjahfd-person-addresses-connection-object": {
    edges: [
      "$90u390jdlsfj;lij923u98fdflkahsf-person-addresses-connection-edges-object",
      "$90uDfadf234kahsf-person-addresses-connection-edges-object",
      "$dfLKJ#)(U(*2349893fdsaf-person-addresses-connection-edges-object",
    ],
    apolloMetadata: {}
  },
  "$90u390jdlsfj;lij923u98fdflkahsf-person-addresses-connection-edges-object": {
    node: "$dslfjal;ksdfj32p94u32p94uoisflksadfjlaksdfj09234-address",
    apolloMetadata: {}
  },
  "$90uDfadf234kahsf-person-addresses-connection-edges-object": {
    node: "$fjbasfkjsdf32894y2398-address",
    apolloMetadata: {}
  },
  "$dfLKJ#)(U(*2349893fdsaf-person-addresses-connection-edges-object": {
    node: "$abfadsfdjflkadjsfhl9898hsdfkafdn-address",
    apolloMetadata: {}
  },
  "$dslfjal;ksdfj32p94u32p94uoisflksadfjlaksdfj09234-address": {
    street: "123 Awesome Street",
    city: "Awesome City",
    apolloMetadata: {}
  },
  "$fjbasfkjsdf32894y2398-address": {
    street: "4 OK Street",
    city: "Awesome City",
    apolloMetadata: {}
  },
  "$abfadsfdjflkadjsfhl9898hsdfkafdn-address": {
    city: "Town Place",
    apolloMetadata: {}
  }
  .....
  ...
}
```
You'd need to write logic to reconstruct the original object structure (which is what Apollo does for you when you use it directly). Implementing this logic yourself *seems* like it would just be reinventing Apollo a fair bit of apollo. And as a reminder, your dealing with observables, so you need to make sure you are subscribing to each related object in the store and glue everything together. Anyway, its non-trivial.

I haven't actually used ngxs in a project yet, but the store format looks similar to ngrx / redux. I think, in order to successfully integrate ngxs with Apollo, you'd need to actually implement a new Apollo caching mechanism that jivved well with the redux store format (which, importantly) is not a flat structure. Building a truly new caching mechanism is, I imagine, a huge undertaking.

This being said, glancing at the [Hermes cache](https://github.com/convoyinc/apollo-cache-hermes), its possible that the Hermes' caching structure, which appears to ***not*** be flattened, *may* provide a solution. I Imagine it would still be a very large project to implement.

**Comment by amcdnl** [comment]
I don't have much experience w/ apollo. If someone else wants to take this on, I'll be happy to help get it in.

**Comment by splincode** [comment]
I think this is outside the scope of this repository and looks more like a plugin for ngxs labs
