### ISSUE TITLE
actions dispatched/handled multiple times

### ISSUE THREAD

**Issue by tpsb** [ngxs/store#477]
### Versions
@angular/core 6.0.7
@ngxs/store 3.1.4

### Repro steps

Please see the [stackblitz example](https://stackblitz.com/edit/angular-gxh1sr).

### Observed behavior

I have a parameterized action and a parameterized selector. 
In component's ngOnInit I'm setting up 3 observables each time with a different parameter. Each time the setup uses a selector to select slice from store and dispatches an action to load the data if it's missing in the store.

Two things should be investigated here, the first point being the main issue.
1. the actions are dispatched once but the action handling methods in the state class or the observables returned from them seem to be subscribed to by the framework multiple times. In the example this can be seen in dev tools and the console - I've logged when the actions are dispatched and when a result is returned from the "service observable".

2. what's the reasoning (provided what is printed by the logger-plugin is correct) behind grouping the actions - it there any place where I could find more info on this? The groupings in this case seem odd.
It's the same action type that is dispatched but those are different instances that should probably be treated distinct. It might be reasonable to group a particular dispatch and success/error but seeing it grouped as in the example is not that intuitive.

I've tried using asap.schedule to disconnect the triggering and resulting action and does help a little as far as what's printed by the logger-plugin but the odd grouping still remains. Also doing it this way does not alleviate the duplication issue described in point 1.

### Desired behavior

Unless I'm doing something wrong here, the _load_ and _success_ actions should be called once for each parameter - I'd expect 3 such pairs.

**Comment by markwhitfeld** [comment]
The problem is caused by the fact that you are doing a load within a select.
When the first load comes back it triggers a change in the other selectors which then results in them doing another load. This is why you are seeing these multiple loads.

I would recommend moving the loading code out of the selection code.
You could just call them up front in the `ngOnInit` or better yet in a resolver on the route. If you want them to check the state first before triggering a load then I would recommend using `store.selectSnapshot(...)` to get the current store data at that point.

The grouping of the actions is so that you can see the relationship between an action and the child actions that are triggered from it. The problem here is that when you have multiple concurrent calls the console gets a bit confused about the grouping. I saw a comment on an issue a while back about removing the grouping until we figure out how to correctly represent this.

Here is your repo which I have modified so that the load happens up front in the `ngOnInit` and it fixed the multiple load problem. I also added a flag so that you can see the difference between concurrent dispatch and sequential dispatch in the logger output.
https://stackblitz.com/edit/ngxs-issue477-1?file=src%2Fapp%2Fapp.component.ts

I suspect that you were expecting to see the logger output that you get if you switch the concurrent flag in the sample off.

**Comment by tpsb** [comment]
Thanks for the reply.


I haven't analyzed the ngxs code and (I think) I do understand what you're saying but I am wondering if the actions should be dispatched before the selector call finishes. From your comment I am concluding that they are dispatched as part of the selector call and this is the cause of the problem. I assume that I would get similar behavior if I dispatched actions from code that handles another action (i.e. if in @Action annotated method I would call dispatch, there might be several levels of such nesting here, right?). Conceptually the problem would go away if the scheduled actions were flattened and dispatched asynchronously after the outer invocation ended. I guess having the information which action triggered a particular action is useful but processing of them should be "disconnected".

Is the behavior I'm currently experiencing like this by design or do you think it might/should be changed?


Regarding the other point (what's printed on the console) the suggested solution (concurrent switch) does fix it as far as the console logs are concerned but the issue I see here is a bit deeper than just the display on the console. You’re suggesting to dispatch another action only once the previous one completes. I wouldn’t want to do it this way, I would like the actions to be handled (or at least the logic they trigger) asynchronously and possibly in parallel (to the extend the browser’s javascript engine allows). In the real app I need to pull several such data objects (lists of values to use in drop downs) and they need to be fetched as fast as possible, it might take too much time to handle those sequentially.

In your example with the concurrent variable set to false the handlers and hence the service calls are done sequentially and they finish in 3 seconds whereas I would expect them to be done within around 1 second. I cannot sacrifice the time just so the logs in the console look good, I hope that's obvious.

**Comment by markwhitfeld** [comment]
The issue here is that with ngxs there is a concept of child actions. This is difficult to visualise in something that is expected to indicate a sequential timeline (logger / redux dev tools) where child actions may be dispatched or complete while other outer actions are also run. We are in the process of making a dev tool that visualises this better. The logger currently has a bug where other outer actions appear as nested actions when prior actions are still in process. It is something that has been reported before but we are focusing on a better dev tool at the moment.

I wasn't suggesting that you dispatch the loads sequentially in your production app because I agree that this doesn't make sense and you would really want to do it concurrently. I was giving that to you as a demonstration of the issue in the logger where concurrent calls get nested in other outer calls and as a sample of what you were expecting to see in the logs. (The end goal of your app would be a usable app as opposed to a nice looking log 😉 )

**Comment by markwhitfeld** [comment]
Regarding the dispatching of actions during your selector call I suspect that you may be misunderstanding how rxjs and reactive concepts work. The selector call does not 'finish' instead the code that you write creates a pipeline through which values will stream as changes are made to the state that defines that selector. Every change to that state will result in the new value running through the `pipe` and triggering whatever you have put there.

If this is surprising to you then I would recommend reading up about rxjs and reactive concepts. It might be a challenge to get your head around at first if you are used to writing imperative code but once it clicks in your mind it's power will become apparent.

**Comment by markwhitfeld** [comment]
In summary, there isn't any issue here (other than the broken visualisation). 
The framework is designed to work this way.

**Comment by tpsb** [comment]
I believe I do get the reactive and rxjs stuff to some extent. 

The thing is that that I'm coming from ngrx and I am trying to replace state management library with ngxs. It looks like the migration isn't as straightforward as I hoped it would be - some patterns that worked with ngrx do not seem to be working with ngxs.
For example the dispatch of action from within a selector was not an issue with ngrx but with ngxs it looks like it's not supported as it has some unexpected effects - action logic is invoked more than once (see my stackblitz example). This added with the log that I'm seeing in the console - the stacking of actions - makes me as a developer wonder if it's me using the library incorrectly or there being something wrong with the library implementation itself. This doesn't seem correct and intuitive if you consider that there were no issues with this kind of approach in ngrx, I hope you get my point here.

Apparently to use ngxs properly I need to change my mindset a bit and most probably spend more time with it to be able to use it properly which I'm definetely going to do. For the time being I've decided to stay with ngrx with the app I'm currently working on and reattempt the ngxs integration sometime in future.

Thank you for the answers so far and if you don't see this as an issue and it's working as designed, please close the issue.
