### ISSUE TITLE
ofActionErrored 

### ISSUE THREAD

**Issue by torbonaut** [ngxs/store#518]
When observing errored Actions it would be useful to catch the error that made the action fail. Can the error be provided?

### Versions

```
* ngxs: 3.0.1
* @angular/core: 6.0.3
```

### Desired behavior

Error available within ofActionErrored

**Comment by splincode** [comment]
Add stackblitz for repro

**Comment by IlCallo** [comment]
This would a really good idea.
Use case: login which can fail for multiple reason, so there could be multiple `throw` statement inside a single action, each with a different message.
When listening to the Action stream it's necessary to understand _which_ error are we dealing with.

Ex.
```typescript
    this.actions.pipe(
      ofActionErrored(Login)
    ).subscribe((action, error) => console.log(error));
```

**Comment by IlCallo** [comment]
I checked the code, it seems to me that this is actually just a matter of exposing the full `ActionContext` instead of mapping it to just the action, changing this

https://github.com/ngxs/store/blob/4ba1032c4b99bd52254ea804344512c5382ba1d1/packages/store/src/of-action.ts#L57

removing altogether `mapAction`.

Or, if you _really_ want to hide the status label, it's just a matter of changing the mapping there

https://github.com/ngxs/store/blob/4ba1032c4b99bd52254ea804344512c5382ba1d1/packages/store/src/of-action.ts#L69-L71

maybe like

```typescript
function mapAction() {
  return map(({action, error}: ActionContext) => { action, error );
}
```

@markwhitfeld shall I make a PR?

**Comment by garthmason** [comment]
This would be very useful - any chance it'll make it in the next release?

**Comment by markwhitfeld** [comment]
@splincode  Any chance you could have a look at how we could do this without introducing a breaking change?

**Comment by splincode** [comment]
@markwhitfeld I will try to see soon

**Comment by markwhitfeld** [comment]
This will be achievable using the `ofActionCompleted` pipe when v3.4 is released.
Use the `@dev` version now to try it out. 
See this comment for the signature of what is returned by this pipe: https://github.com/ngxs/store/issues/710#issuecomment-447647487
This will be in the docs once PR #726 is merged

**Comment by IlCallo** [comment]
🎉🎉

Even though, the semplicity of returning the error via ofActionErrored would be the best.

If you consider this to be a breaking change,  can we hope to see it in version 4.0 maybe?
