### ISSUE TITLE
[Question] When is the next release planned?

### ISSUE THREAD

**Issue by ToxSickCoder** [ngxs/store#599]
We're currently blocked from using NGXS by our CSP because of `unsave-eval`. 

This, however, is fixed by [this PR](https://github.com/ngxs/store/pull/569). 

Is there any indication when the next NGXS release that includes this PR will be released?

**Comment by splincode** [comment]
@markwhitfeld ping

**Comment by eranshmil** [comment]
Meanwhile, you can use the [Development Builds](https://ngxs.gitbook.io/ngxs/getting-started/installation#development-builds).

**Comment by markwhitfeld** [comment]
The development builds were not being published by the CI.
I was given admin rights today and have fixed the build.
@ToxSickCoder There is now a new `@dev` version you can try with this feature in it.
Please let me know if the issue is fixed for you.
Regarding the next official release, it will have to be a minor release because of the features that have been added on master. We are waiting for a few more changes to master before we publish a new official release.

**Comment by ToxSickCoder** [comment]
Ok, great! We were a bit worried since the last release was 3 months ago. It's good to hear that it was just a problem with the CI.

I just installed the dev version, and it seems to have fixed our CSP problem. Thanks!

**Comment by jordandh** [comment]
It looks like there have been commits recently to support Angular 7. Will there be a release soon with Angular 7 support? NGXS is the last library we are waiting on for official Angular 7 support.

**Comment by jordandh** [comment]
I see now that it is part of milestone 5 (3.3.0) https://github.com/ngxs/store/milestone/5
Thanks for the hard work everyone!

**Comment by eranshmil** [comment]
You can have this changes right now if you use the dev builds.
``` bash
yarn add @ngxs/{store,logger-plugin}@dev
```
