### ISSUE TITLE
Docs Bug?  Return value from store.dispatch

### ISSUE THREAD

**Issue by mann-david** [ngxs/store#606]
Possible documentation bug?  According to https://ngxs.gitbook.io/ngxs/concepts/store#dispatching-actions, "The Observable that a dispatch returns has a void type".  If my brain isn't totally fried after a long day, it looks like it's returning the whole state instead of void.  Am I missing something?  Did this change recently?

### Versions

```
* ngxs: 3.2.0
* @angular/core: 6.1.10
```

### Repro steps

Stackblitz: https://stackblitz.com/edit/ngxs-simple-izggo9

1. Open the dev tools console
2. Click the Count button
3. The entire state is logged to the console

### Observed behavior
Whole state is returned as payload of Observable

### Expected behavior
According to https://ngxs.gitbook.io/ngxs/concepts/store#dispatching-actions, "The Observable that a dispatch returns has a void type".  I would expect `undefined` to be logged.

### Mention any other details that might be useful (optional)
IMHO, it would be better if the Observable did have a void type.  I can get state other ways if I need it, but this makes it hard to do `withLatestFrom` as the docs show and get whatever just changed.

**Comment by NarHakobyan** [comment]
Hi @mann-david, Yes you are right, it's returning full state instead of void, but I think it will be more comfortable if dispatch subscription will return data from action handler, I have already created PR for that
https://github.com/ngxs/store/pull/634

**Comment by markwhitfeld** [comment]
You should not count on it returning a value as stated correctly in the docs.
We haven't done that change because it may be a breaking change for anyone that expected the state value to be returned as it is.
The reason for the intended void return is to prevent the use of this observable for the wrong thing.
For example user's may be tempted to chain these observables or select state slices, thereby skipping the correct mechanisms for doing these things in the framework.

**Comment by NarHakobyan** [comment]
@markwhitfeld yes, but we are missing return value of Action Handler, it's it's not allowing to do dispatches by chain

**Comment by splincode** [comment]
return value depracated since 4.0.0
https://github.com/ngxs/store/issues/827
