### ISSUE TITLE
@Selector is changing the initial state without mutation

### ISSUE THREAD

**Issue by Kush5900** [ngxs/store#607]
### Versions

```
* ngxs: 3.2.0
* @angular/core: 6.0.3
```

### Repro steps

Stackblitz  link: https://stackblitz.com/edit/angular-ngxs-selector-change-state-issue

* Create a @selector that uses map to change and group sub array into three grouped arrays
* Use this @selector with @select in any component to display grouped data
* Use  @select again to select from immutable state and display how it is with changes

### Observed behavior

```
i'm using NgxsOnInit to fetch my data from api to be initialized to the ListState and mutate state with setState and in my component i'm calling  getGrouped Selector which change the sub array of list state and its working but when i call the other selector that return state without map or any modification the getList Selector is return what getGroup Selector changed not the original data fetched from api. with causing not to display list data because its changed.

```
![state-question](https://user-images.githubusercontent.com/25362017/47210866-6355fb80-d394-11e8-915b-889c236554f6.png)

### Desired behavior
the initial state must not change and any Selector wish to select from state must get the unchanged state unless its mutated by using Action

**Comment by poloagustin** [comment]
You have two problems and I think I can only help quickly with one of them.
The first one would be that typescript is throwing you one error in this line
<img width="367" alt="screen shot 2018-10-19 at 08 34 07" src="https://user-images.githubusercontent.com/1960458/47215997-cab28200-d379-11e8-8291-f5d85b3bdfdf.png">
First I think you wanna fix that in order to continue. I'm almost sure you're not defining your interfaces correctly in relation to what you're gonna set in the `setState`.
The second being this line
<img width="349" alt="screen shot 2018-10-19 at 08 36 49" src="https://user-images.githubusercontent.com/1960458/47216074-23821a80-d37a-11e8-8a36-1816e57b5d50.png">
You most definitely should not be setting new attributes to the elements of the collection. The idea behind `Array.map` is that you want to return new objects so the immutable way of mapping an array would end up returning something like
```
return {
  ...item,
  list: columns
};
```

Hope this helps 🙂

**Comment by Kush5900** [comment]
@poloagustin i changed on that return item line but it's not helping and i have issues with interfaces too since i can't find how i will return state.lists = [{object},{object}] i'm using list[0] so i get array of objects that i want to modifiy... but the problem is the state changes after Selector decorator which suppose to return a copy of state!

**Comment by Kush5900** [comment]
i managed to fix that map issue now it wasn't interfaces issue... it was the way i was using setState.. so now typeScript is not throwing error and i can return state without list[0]. but the problem persit and now its pretty clear to understand. thanks

**Comment by poloagustin** [comment]
For what I understand your problem is that you don't want the state to mutate by calling your `@Selector`, right?
<img width="988" alt="screen shot 2018-10-20 at 01 51 15" src="https://user-images.githubusercontent.com/1960458/47251468-d00bdd00-d40a-11e8-8ea5-5c0b9f958879.png">
Try commenting the line where you mutate each list element like such
<img width="989" alt="screen shot 2018-10-20 at 01 51 34" src="https://user-images.githubusercontent.com/1960458/47251520-dd28cc00-d40a-11e8-82e8-a3ce3b2a9be6.png">

**Comment by markwhitfeld** [comment]
@Kush5900 if you want to fix all the places that you are incorrectly mutating the original state then turn `developmentMode` on in the options. It will freeze the objects to prevent this type of thing

**Comment by Kush5900** [comment]
it's working now thanks @poloagustin  @markwhitfeld  but why the state get mutated by Selector i though the state is immutable.

**Comment by splincode** [comment]
@Kush5900 the default state is mutable

You can use:

- enable developmentMode for track mutation
- https://github.com/ngxs-labs/immer-adapter
- Immutable wrapper (DeepReadonly TypeScript generics)
- Immutable operators (since v3.5)
