### ISSUE TITLE
Breaking change 3.3.0

### ISSUE THREAD

**Issue by splincode** [ngxs/store#690]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

When update from 3.3.2 to 3.3.3

![image](https://user-images.githubusercontent.com/12021443/49358319-4b87cc00-f6e3-11e8-8a91-90e6a64c2f39.png)

**Comment by splincode** [comment]
cannot reproduce

**Comment by markwhitfeld** [comment]
This is an issue. The properties of the options should be optional. I'll fix it in a PR and release a fix

**Comment by splincode** [comment]
@markwhitfeld I can't reproduce!!!

**Comment by markwhitfeld** [comment]
Yeah, I just realised that `NgxsModule.forRoot` takes `ModuleOptions` which is declared as follows:
```TS
export type ModuleOptions = Partial<NgxsConfig>;
```
The reason why the issue above was experienced is because the user was using the internal `NgxsConfig` interface directly as opposed to the `ModuleOptions` type which is required by the `forRoot` method.
Closing because this is not a breaking change to the public api, it was the user's decision to use an internal api.
