### ISSUE TITLE
Route selector for the router plugin

### ISSUE THREAD

**Issue by arturovt** [ngxs/store#912]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
```typescript
import { RouterState } from '@ngxs/router-plugin';

@Component({ ... })
export class SomeNestedComponent {
  @Select(RouterState.state) public router$: Observable<RouterStateSnapshot>;

  constructor() {
    this.router$.subscribe((state) => {
      console.log(state.root.firstChild.firstChild.firstChild);
    });
  }
}
```

## Expected behavior
```typescript
import { RouterState } from '@ngxs/router-plugin';

@Component({ ... })
export class SomeNestedComponent {
  @Select(RouterState.route(SomeNestedComponent)) public route$: Observable<ActivatedRoute>;

  constructor() {
    this.route$.subscribe((route) => {
      console.log(route.data.someResolvedData);
    });
  }
}
```

**Comment by markwhitfeld** [comment]
Why wouldn't you just inject the `ActivatedRoute` into your component?

**Comment by arturovt** [comment]
@markwhitfeld 
Sure, what if I would like to "watch" resolved data change? Basic example:
```ts
{
  path: 'cat/:name',
  resolve: { cat: CatResolver },
  runGuardsAndResolvers: 'paramsChange'
}
```
Inside the component:
```ts
public cat$ = this.store.select(RouterState.route(SomeNestedComponent)).pipe(
  map(({ data }) => data.cat)
);
```
Inside the template:
```html
<app-cat-information [cat]="cat$ | async"></app-cat-information>
```

I understand that we shouldn't increase the `@ngxs/router-plugin` functionality. What about a subpackage like `@ngxs/router-plugin/resolve` where we could expose a selector?

**Comment by NicolasLiveris** [comment]
Hi guys !
To make this selection, I use a joining selector.
https://ngxs.gitbook.io/ngxs/concepts/select#joining-selectors
```typescript
  @Selector([RouterState])
  static activityId(state: OptionsState, router: any) {
    return router.state.root.firstChild.firstChild.params.id;
  }
```
It works but it may affect performance.

**Comment by arturovt** [comment]
@NicolasLiveris 
Hello, the type of `firstChild` is `ActivatedRoute | null`, so this maybe lead to some kind of undefined behavior. Also, image a situtation where you've got some 15x nested component, so you will have to write `firstChild` 15 times?

**Comment by thomas-ama** [comment]
### Issues
> Why wouldn't you just inject the `ActivatedRoute` into your component?

@markwhitfeld 
I can see two cases where injecting `ActivatedRoute` is not OK.

1) `ActivatedRoute` cannot be injected in services.

2) Some parameters (`data` and `params`  e.g.) are merged from root component to the deepest one in the `Tree<ActivatedRouteSnapshot>`.
If `RootComponent` defines the following `data`:
```
pet: "dog",
food: "tomatoes",
```
And `ChildComponent` defines those:
```
pet: "cat",
name: "Jack",
```
Then, if `ActivatedRoute` is injected in `ChildComponent`, `route.snapshot.data` will return:
```
pet: "cat", // overwritten
food: "tomatoes",
name: "Jack",
```
Sometimes, `pet: "dog"` from `RootComponent` is needed (the original value, not the overwritten one) in `ChildComponent`.

A solution is to call `route.parent.snapshot.data`. But if there are 3 components between the `RootComponent` and the current component, that's not convenient (`route.parent.parent.parent.parent.snapshot.data`) and brittle (if one component is inserted between the `RootComponent` and the current component).

### My temporary solution
**Custom Router State Serializer**
I defined a _Custom Router State Serializer_ returning the `IRouterStateSerialized` interface:

```
export interface IRouterStateSerialized
{
  global: IRouterState // contains all merged params, data, etc => same state as the deepest component
  components: Map<string, IRouterState>; // string = component name
}

export interface IRouterState
{
  url: string;
  queryParams: Params;
  params: Params;
  data: Data;
}
```

Now I can retrieve a component router state as follows
```
const routerState = this.store.selectSnapshot<IRouterStateSerialized>(RouterState.state);
const myComponentRouterState: IRouterState = routerState.components.get('MyComponent');
```
But:

- Using component names as strings is brittle
- It is not implementation-independent (I'm using the `get` method of `Map`)
So I prefer using a selector that returns directly an interface.

**Component state selector**
Then, I defined a lazy memoized / joining selector (yes that's ugly) in the `AppState`:
```
  @Selector([RouterState])
  public static componentRouterState(state: IAppStateModel, routerState: RouterStateModel): IRouterState
  {
    return (componentName: string) =>
    {
      return (routerState.state as IRouterStateSerialized).components.get(componentName);
    };
  }
```
Note: TypeScript complains about `(routerState.state as IRouterStateSerialized)` because it is not aware of custom serializer I guess:
`Conversion of type 'RouterStateSnapshot' to type 'IRouterStateSerialized' may be a mistake because neither type sufficiently overlaps with the other`

I use it like this

```
const componentRouterStateSelector = this.store.selectSnapshot(NoteTakingState.componentRouterState);
componentRouterStateSelector('MyComponent') // returns IRouterState
```

This method is far from perfect but it solves the two problems mentioned above.

**Comment by arturovt** [comment]
@thomas-ama Interesting solution! And also you're right that `ActivatedRoute` is provided into component's `providers` under the hood, thus we cannot access it anywhere except views. What would you propose by the way? Do you agree with that selector feature that's mentioned on the top of this issue? :wink:

**Comment by thomas-ama** [comment]
> Do you agree with that selector feature that's mentioned on the top of this issue?

Yes but it should be possible to add a custom serializer to transform `ActivatedRoute` if needed.

> Also I'm afraid that MyComponent class name can be mangled in the production mode, I think we could handle this only using reference to the class.

That's indeed a better solution.

> So we could walk the tree and check component instanceof ComponentConstructor.

What's `ComponentConstructor`? Do you have a link to documentation?
I tried to find something similar (parent class of all components).

My solution is a proto and is not perfect at all. That's how I found your issue ;-)

**Comment by arturovt** [comment]
@thomas-ama 
`ComponentConstructor` is just some class like `MyComponent` :smile:

**Comment by thomas-ama** [comment]
I updated my solution to remove the typescript error. I replaced:
```
@Selector([RouterState])
public static componentRouterState(state: IAppStateModel, routerState: RouterStateModel): IRouterState
{
  return (componentName: string) =>
  {
    return (routerState.state as IRouterStateSerialized).components.get(componentName);
  };
}
```

with

```
@Selector([RouterState])
public static componentRouterState(state: IAppStateModel, routerState: RouterStateModel<IRouterStateSerialized>): IRouterState
{
  return (componentName: string) =>
  {
    return routerState.state.components.get(componentName);
  };
}
```

**Comment by arturovt** [comment]
@thomas-ama 
The problem is we deal with the tree of `ActivatedRoute` classes, I would propose:
```ts
public static route<T>(component: Type<T>) {
  return createSelector([RouterState], (state: RouterStateModel) => {
    let route: ActivatedRoute | null = null;
    let firstChild = state.root.firstChild;

    while (firstChild) {
      if (firstChild.component instanceof component) {
        route = firstChild;
        break;
      }

      firstChild = firstChild.firstChild;
    }

    return route;
  });
}
```

P.S. - this is just a pseudocode, but can be implemented similar to that. Also this function call stays monomorphic, so V8 is able to optimize it + `while` loop is fast. What do you think?
