### ISSUE TITLE
Use Action decorator without State decorator in a service

### ISSUE THREAD

**Issue by ahnpnl** [ngxs/store#927]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

At the moment, I always do
```
@State<FooStateModel>({
  name: 'foo',
})
export class FooState {
@Action(UpdateFoo)
  updateFoo({ patchState }: StateContext<FooStateModel>, { payload }: UpdateFoo) {
      // my logic here
  }
}
```

## Expected behavior

It would be nice if I could do
```
export class FooService {
    @Action(UpdateFoo)
     handleUpdateFoo({ payload }: UpdateFoo) {
      // my logic here to handle something else, could be dispatch another action or trigger other services
     }
}
```
My purpose is instead of injecting `Actions` into `FooService` and subscribe to it, I would like to use Action decorator to listen to the action and auto subscribe/unsubscribe it.

## What is the motivation / use case for changing the behavior?

Less boilercode when subscribe to an action

## Environment

<pre><code>
Libs:
- @angular/core version: X.Y.Z
- @ngxs/store version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 73.0.3683.75
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.15.1  
- Platform: Windows  

Others:

</code></pre>

**Comment by splincode** [comment]
https://github.com/ngxs-labs/emitter

**Comment by ahnpnl** [comment]
I think right now when using Action decorator, without checking documentation there is no clear error message to inform the user that it is only used together with State decorator and I'd love to use that Action decorator independently instead of installing an extra package like emitter.

**Comment by splincode** [comment]
Proposal

```ts
class State {
  
   @Action(AddTodo)
   public addTodo(ctx: StateContext, action, { resolve, reject }: ActionContext) {
      resolve(true); // custom cancel success
      reject(false); // custom cancel with error
   }

}
```

**Comment by ahnpnl** [comment]
hi @splincode , is it possible also to include state operator functions for your example, something like an option to pass in either `actionDispatched`, `actionSuccessful`, `actionError` or `actionCompleted` ? In the end, it is something like we can replace 
```
this.action$.pipe(
    ofActionDispatched(AddToDo),
).subscribe()
```
with `@Action`

**Comment by cuddlecake** [comment]
I'm actually leaving a +1 here.

Having the Feature to listen to Actions in Services without injecting `Actions` would be a great feature.

This would make ngxs double as both, a framework for redux, as well as a framework for event sourcing in the frontend.

**Comment by arturovt** [comment]
@cuddlecake @ahnpnl 

Gentlemen, this is not possible because the `@Action` decorator drastically relies on the `@State` decorator. They work in conjuction.

Handling actions directly in state classes gives an opportunity to centralize business in a single place without having to run between multiple classes. My junior (even middle) developers would be super confused if they had to switch between classes and to think what action belongs to which state class :relaxed: 

> duplication is far cheaper than the wrong abstraction (c) Sendi Metz

There will be no possibility to provide a strict style guide for the project as every new upcoming developer will have to think WHERE and HOW to handle actions.

Domain driven design layering in the Redux can be divided into 3 layers - presentation, domain and data. Where domain is a conjuction of actions + state.

![image](https://user-images.githubusercontent.com/7337691/58290920-1c196880-7dc4-11e9-8b30-b58077d8a499.png)

By using actions inside the service - you force service to know about actions, service has to know nothing, make services small and dumb so they can be responsible only for one thing.
